### ISSUE TITLE
HAXM v7.3.0 causes Kernel Panic on Mac OS 10.13.6 (Hackintosh)

### ISSUE THREAD

**Issue by TheArch** [intel/haxm#101]
Hi. It's an older iMac with Intel Core 2 Duo T9300 2.5 GHz Prozessor. If you don't like to support Hackintoshes, than it's not a big Problem. But if it's not hard to find the problem it would be nice.

Anonymous UUID:       7B0CB048-AD3B-D799-9DD0-0FE11C7B776D

Wed Sep 19 19:27:24 2018

*** Panic Report ***
panic(cpu 0 caller 0xffffff8010f8776f): Kernel trap at 0xffffff7f947fc102, type 13=general protection, registers:
CR0: 0x0000000080010033, CR2: 0x0000000133bfa030, CR3: 0x000000001b643000, CR4: 0x00000000000026e0
RAX: 0x0000000020100800, RBX: 0x0000000000000002, RCX: 0x00000000c0000103, RDX: 0x0000000000000000
RSP: 0xffffff80e18139b8, RBP: 0xffffff80e1813a10, RSI: 0x000000000000001b, RDI: 0x00000000c0000103
R8:  0xffffff8030cefb60, R9:  0xffffff801168a630, R10: 0xffffff80e1813a68, R11: 0xffffff7f91b74810
R12: 0xffffff8024a82800, R13: 0xffffff7f9480cfc0, R14: 0xffffff7f9480d180, R15: 0xffffff8021774c00
RFL: 0x0000000000010046, RIP: 0xffffff7f947fc102, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000133bfa030, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff8010d4c290 : 0xffffff8010e6c1c6 
0xffffff8010d4c2e0 : 0xffffff8010f95274 
0xffffff8010d4c320 : 0xffffff8010f87544 
0xffffff8010d4c390 : 0xffffff8010e1e1e0 
0xffffff8010d4c3b0 : 0xffffff8010e6bc3c 
0xffffff8010d4c4e0 : 0xffffff8010e6b9fc 
0xffffff8010d4c540 : 0xffffff8010f8776f 
0xffffff8010d4c6b0 : 0xffffff8010e1e1e0 
0xffffff8010d4c6d0 : 0xffffff7f947fc102 
0xffffff80e1813a10 : 0xffffff7f947e8442 
0xffffff80e1813a50 : 0xffffff7f947e8752 
0xffffff80e1813ab0 : 0xffffff7f947ece3a 
0xffffff80e1813ae0 : 0xffffff7f947e783e 
0xffffff80e1813b50 : 0xffffff80110d6eb1 
0xffffff80e1813b80 : 0xffffff80110cc6bf 
0xffffff80e1813c00 : 0xffffff80110bef8b 
0xffffff80e1813e00 : 0xffffff80112f7c63 
0xffffff80e1813e30 : 0xffffff801134835c 
0xffffff80e1813f40 : 0xffffff8011403968 
0xffffff80e1813fa0 : 0xffffff8010e1e9c6 
      Kernel Extensions in backtrace:
         com.intel.kext.intelhaxm(7.3)[65C423BE-0315-30BD-8DA8-CABFE8487E10]@0xffffff7f947e6000->0xffffff7f9480dfff

BSD process name corresponding to current thread: qemu-system-i386
Boot args: -no_compat_check

Mac OS version:
17G65

Kernel version:
Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Kernel UUID: 1AE5ACFD-3B6F-3D74-AD52-31F1430DBC6F
Kernel slide:     0x0000000010c00000
Kernel text base: 0xffffff8010e00000
__HIB  text base: 0xffffff8010d00000
System model name: iMac7,1 (Mac-F4238CC8)

System uptime in nanoseconds: 427363865840761
last loaded kext at 261056714656597: com.apple.filesystems.apfs	748.51.0 (addr 0xffffff7f94816000, size 999424)
last unloaded kext at 261156477671235: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f9480e000, size 32768)
loaded kexts:
com.intel.kext.intelhaxm	7.3.0
at.obdev.nke.LittleSnitch	4740
com.parrotgeek.SIPManager	1
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.AppleHDA	274.12
com.apple.kext.AMDLegacyFramebuffer	1.6.8
com.apple.AGDCPluginDisplayMetrics	3.20.13
com.apple.ATIRadeonX2000	10.0.4
com.apple.driver.pmtelemetry	1
com.apple.driver.AppleBacklight	170.9.10
com.apple.driver.AppleMCCSControl	1.5.5
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.7f10
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.kext.AMD2600Controller	1.6.8
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	6.0.7f10
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleIRController	353
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	407.50.6
com.apple.iokit.SCSITaskUserClient	404.30.2
com.apple.driver.AirPort.BrcmNIC	1241.31.1a9
com.apple.driver.AppleAHCIPort	329.50.2
com.apple.driver.AppleIntelPIIXATA	2.5.1
com.apple.driver.AppleFWOHCI	5.5.9
com.apple.iokit.AppleYukon2	4.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	220.50.1
com.apple.nke.applicationfirewall	183
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	220.50.1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	274.12
com.apple.kext.OSvKernDSPLib	526
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	519.20
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOSurface	211.15
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOAVBFamily	680.2
com.apple.plugin.IOgPTPPlugin	680.15
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.iokit.IOFireWireIP	2.2.9
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.7f10
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.7f10
com.apple.iokit.IOBluetoothFamily	6.0.7f10
com.apple.driver.AppleHDAController	274.12
com.apple.iokit.IOHDAFamily	274.12
com.apple.iokit.IOAudioFamily	204.4
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSSE	1.0
com.apple.AppleGPUWrangler	3.20.13
com.apple.AppleGraphicsDeviceControl	3.20.13
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.kext.AMDLegacySupport	1.6.8
com.apple.iokit.IOGraphicsFamily	519.20
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOSCSIMultimediaCommandsDevice	404.30.2
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.iokit.IOATAPIProtocolTransport	3.5.0
com.apple.iokit.IOAHCIBlockStorage	301.40.2
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOAHCIFamily	288
com.apple.iokit.IOATAFamily	2.5.3
com.apple.iokit.IOFireWireFamily	4.7.2
com.apple.driver.usb.AppleUSBEHCIPCI	1.2
com.apple.driver.usb.AppleUSBUHCIPCI	1.2
com.apple.driver.usb.AppleUSBUHCI	1.2
com.apple.driver.usb.AppleUSBEHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.70.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.70.2
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.DiskImages	480.60.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOTimeSyncFamily	680.15
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

EOF
Model: iMac7,1, BootROM IM71.007A.B03, 2 processors, Intel Core 2 Duo, 400 MHz, 6 GB, SMC 1.20f4
Graphics: ATI Radeon HD 2600 Pro, ATI,RadeonHD2600, PCIe
Memory Module: BANK 0/DIMM0, 2 GB, DDR2 SDRAM, 667 MHz, 0x7F7F9E0000000000, 0x565332475344533636374432202020202020
Memory Module: BANK 1/DIMM1, 4 GB, DDR2 SDRAM, 667 MHz, 0x0000000000000000, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.7f10, 3 services, 26 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Samsung SSD 840 EVO 1TB, 1 TB
Parallel ATA Device: MATSHITADVD-R   UJ-85J
USB Device: USB 2.0 Bus
USB Device: Built-in iSight
USB Device: USB 2.0 Bus
USB Device: USB Bus
USB Device: Bluetooth HCI
USB Device: USB Bus
USB Device: IR Receiver
USB Device: USB Bus
USB Device: USB Bus
USB Device: BCM2045A0
USB Device: USB Receiver
USB Device: USB Bus
Thunderbolt Bus:

**Comment by raphaelning** [comment]
Thanks for the report. We no longer test HAXM on Core 2 Duo or any 7-plus-year-old CPUs that lack the EPT feature, so breakages can happen. Coincidentally, we've also received a similar host crash report from a Windows user of HAXM 7.3.0 on a very old Xeon CPU. If we can fix both with a small effort, we'll do it :-)

Using the information you provided, I have come up with a possible root cause of the issue. Basically, HAXM 7.3.0 includes a patch (#61) that assumes the presence of a CPU feature known as _RDTSCP_, which probably doesn't exist on Core 2 Duo. I'm working on a fix for that; meanwhile, could you confirm the following:

1. That you did not have this issue when using HAXM 7.2.0.
1. That your CPU indeed lacks the RDTSCP feature. One way to do it is to download cpuid.py (a small Python program), run `python cpuid.py` and show me the output.

**Comment by TheArch** [comment]
Hi. Thank you for your fast response. I'm not sure if HAXM 7.2.0 worked. I will try to find that version and install it. Here are the result of example.py / cpuid.py . Greetings from munich.

Vendor ID : GenuineIntel
CPU name  : Intel(R) Core(TM)2 Duo CPU     T9300  @ 2.50GHz

Vector instructions supported:
SSE       : Yes
SSE2      : Yes
SSE3      : Yes
SSSE3     : Yes
SSE4.1    : Yes
SSE4.2    : --
SSE4a     : --
AVX       : --
AVX2      : --
BMI1      : --
BMI2      : --
L3 Monitoring : Yes
L3 Occupancy  : Yes
L3 Total BW   : Yes
L3 Local BW   : --

---

CPUID    A        B        C        D
00000000 0000000a 756e6547 6c65746e 49656e69
00000001 00010676 00020800 0008e3bd bfebfbff
00000002 05b0b101 005657f0 00000000 2cb4304e
00000003 00000000 00000000 00000000 00000000
00000004 04000121 01c0003f 0000003f 00000001
00000005 00000040 00000040 00000003 03122220
00000006 00000001 00000002 00000001 00000000
00000007 00000000 00000000 00000000 00000000
00000008 00000400 00000000 00000000 00000000
00000009 00000000 00000000 00000000 00000000
0000000a 07280202 00000000 00000000 00000503
80000000 80000008 00000000 00000000 00000000
80000001 00000000 00000000 00000001 20100800
80000002 65746e49 2952286c 726f4320 4d542865
80000003 44203229 43206f75 20205550 54202020
80000004 30303339 20402020 30352e32 007a4847
80000005 00000000 00000000 00000000 00000000
80000006 00000000 00000000 18008040 00000000
80000007 00000000 00000000 00000000 00000000
80000008 00003024 00000000 00000000 00000000

**Comment by raphaelning** [comment]
Grüß Gott :-)

> 80000001 00000000 00000000 00000001 20100800

Thanks, this does confirm that your CPU lacks support for RDTSCP.

> I'm not sure if HAXM 7.2.0 worked. I will try to find that version and install it.

You can download it from here: https://github.com/intel/haxm/releases/tag/v7.2.0

Please uninstall 7.3.0 before installing 7.2.0. If you installed HAXM through Android Studio, you can open SDK Manager and uninstall it from there.

**Comment by raphaelning** [comment]
BTW, in the macOS crash dump:

> RCX: 0x00000000c0000103

is the address of the `IA32_TSC_AUX` model-specific register (MSR), which is not present on CPUs that lack the RDTSCP feature. Attempt to read it using the `RDMSR` instruction (as pointed to by `RIP: 0xffffff7f947fc102`) will lead to a General Protection Fault (`type 13=general protection`).

**Comment by bfabiszewski** [comment]
I can confirm that downgrading to 7.2.0 seems to fix [my crashing problem](https://github.com/intel/haxm/issues/88#issuecomment-432156073).
