### ISSUE TITLE
vcpu_panic: Unexpected MMIO instruction (opcode 0xF7)

### ISSUE THREAD

**Issue by LukeUsher** [intel/haxm#12]
The platform I am trying to virtualize with HAXM uses the TEST opcode to check the value of an MMIO register. 

HAXM's fast mmio implementation doesn't handle this and the vcpu implementation panics.

![image](https://user-images.githubusercontent.com/740003/33246272-819d5fc4-d30a-11e7-92f6-eb37755270d4.png)

**Comment by raphaelning** [comment]
Thanks for the report. Indeed HAXM's x86 instruction emulation logic is incomplete. I think it needs some refactoring, which will make it easier for us to add support for more instructions.

**Comment by AlexAltea** [comment]
@LukeUsher PR #42 should have fixed this issue. Can confirm it?

**Comment by raphaelning** [comment]
Yes, thanks for the reminder! The only `TEST` opcodes that may access memory are `0xF6`, `0xF7`, `0x84` and `0x85`, all of which should be supported by now.
