### ISSUE TITLE
can't support more than 4G memory for guest?

### ISSUE THREAD

**Issue by hujun-open** [intel/haxm#13]
setup:
 - host: windows 7 professional 64bit
 - guest: centos 7
 - qemu 2.10.92
 - haxm 6.2.1
 - issue: when assign 4096M or more memory to the guest, I got following error message:
```
E:\qemuvm\vm-svr>qemu-system-x86_64 -accel hax -hda centos-1.vdi -m 4096
HAX is working and emulator runs in fast virt mode.
Failed to allocate 0 memory
hax_transaction_commit: Failed mapping @0x0000000000000000+0xc0000000 flags 00
hax_transaction_commit: Failed mapping @0x0000000100000000+0x40000000 flags 00
VCPU shutdown request
VCPU shutdown request
```
if I change memory to 4095M, guest VM boot up without issue
```
E:\qemuvm\vm-svr>qemu-system-x86_64 -accel hax -hda centos-1.vdi -m 4095
HAX is working and emulator runs in fast virt mode.
```

**Comment by hujun-open** [comment]
ok, it seems this is a known limitation according to the [official install instruction](https://software.intel.com/en-us/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-windows);

could this limitation be removed in future release?

**Comment by raphaelning** [comment]
This is a limitation of the current HAXM API. There's a simple way to fix it, but nevertheless it will require a change on the QEMU side. The HAXM-side change can definitely be included in the next HAXM release.

**Comment by hujun-open** [comment]
Thanks for accepting this!
I also raised a request on qemu side for qemu side work: https://bugs.launchpad.net/qemu/+bug/1735576

**Comment by YuleiWang** [comment]
"QEMU side work" will be also from HAXM dev team who will contribute a patch to QEMU for this issue. The team has been working on both changes. We target to make the next HAXM release and submit the patch to QEMU by end of Dec.

**Comment by hujun-open** [comment]
Thanks for the clarification; I have updated the qemu report accordingly

**Comment by hujun-open** [comment]
is there an update on qemu side work? I have tried latest qemu release v2.11.1 and haxm 7.0, still same problem

**Comment by raphaelning** [comment]
The patch has been pulled into QEMU's master branch:

https://lists.gnu.org/archive/html/qemu-devel/2018-02/msg01768.html
https://lists.gnu.org/archive/html/qemu-devel/2018-02/msg03317.html

but apparently not into any release yet. So I guess you just need to wait for the next QEMU release, or build QEMU yourself.

BTW, I did include the [launchpad link](https://bugs.launchpad.net/qemu/+bug/1735576) in the commit log of the patch, but unfortunately that didn't trigger an automatic update to the bug...

**Comment by hujun-open** [comment]
thanks for the update;
I have built qemu from latest source, it works!
