### ISSUE TITLE
SYSTEM_SERVICE_EXCEPTION IntelHaxm.sys

### ISSUE THREAD

**Issue by alejerry** [intel/haxm#147]
Hi,
on my pc windows 10, when I start the android virtual device, windows crashes with blue screen SYSTEM_SERVICE_EXCEPTION and file error IntelHaxm.sys.
All software, driver, etc are updated.
I have a Intel Core Quad Q9450, 4GB Ram and graphic card nvidia.
I hope you can help me solve the problem

Thanks
Alessandro

**Comment by wcwang** [comment]
Could you provide any dump file for further analysis? Usually the dump files could be found at C:\Windows\Minidump. Thanks.

**Comment by alejerry** [comment]
Yes, I attachment del file dmp. Thanks

[121918-8578-01.zip](https://github.com/intel/haxm/files/2694005/121918-8578-01.zip)

**Comment by raphaelning** [comment]
Sorry for the delay, I just got back from vacation. This looks like a duplicate of #101. We have already fixed it on the master branch with #103, but haven't made a new release that includes this fix. For now, you can downgrade to [HAXM 7.2.0](https://github.com/intel/haxm/releases/tag/v7.2.0).

**Comment by alejerry** [comment]
Thank you very much! Problem solved!

Alessandro
