### ISSUE TITLE
OSX SHA-256 does not match

### ISSUE THREAD

**Issue by Xsixteen** [intel/haxm#165]
Hello,

OSX Sha-256 does not match what is listed on downloads page.  Reported 
SHA256(haxm-macosx_v7_3_2.zip)= 48c87dc4c2e026a367ac5e444308ee486f5ea7d5672f87a12670a53edca7a74e

**Comment by raphaelning** [comment]
Thanks for the report. Are you talking about HAXM 7.4.1 or 7.3.2? At first I thought you were trying to verify the checksum of the latest 7.4.1 release, but then I realized you had run `openssl dgst -sha256` on 7.3.2.

Actually, I've downloaded both files and recomputed their SHA-256 checksum:

```
SHA256(haxm-macosx_v7_4_1.zip)= 613c2ee9725af7febdb1b0adef0f8f487aa610f0fa4b75d89dad267145cd2293
SHA256(haxm-macosx_v7_3_2.zip)= 48c87dc4c2e026a367ac5e444308ee486f5ea7d5672f87a12670a53edca7a74e
```

They are the same as listed on the Releases page.

**Comment by Xsixteen** [comment]
That is correct it is haxm-macosx_v7_3_2.zip 

openssl dgst -sha256 haxm-macosx_v7_3_2.zip 
SHA256(haxm-macosx_v7_3_2.zip)= 48c87dc4c2e026a367ac5e444308ee486f5ea7d5672f87a12670a53edca7a74e

I realized I didn't include the download page: https://software.intel.com/en-us/articles/intel-hardware-accelerated-execution-manager-intel-haxm

**Comment by raphaelning** [comment]
I see what you mean now, thanks!

1. Please try the latest release from here: https://github.com/intel/haxm/releases/latest
1. The HAXM download page on intel.com is maintained by another team at Intel, and we'll ask them to update it. I'd recommend that you download HAXM from the above link, i.e. our GitHub Releases page.

**Comment by raphaelning** [comment]
We have taken down the old HAXM homepage. That URL now redirects to our GitHub page.
