### ISSUE TITLE
HAXM triggers FPU DNA exception

### ISSUE THREAD

**Issue by krytarowski** [intel/haxm#166]
Summary: 
HAXM from HEAD (as of 2019-02-11) triggers FPU DNA (Device Not Available) exception.

FPU DNA is triggered with calling FPU instructions (fxsave) inside kernel without FPU context available.

**Host Environment**
NetBSD/amd64 8.0 and HEAD (probably any supported version)

* HAXM version: 
HAXM from HEAD (as of 2019-02-11)

* Host OS version: 
NetBSD chieftec 8.99.34 NetBSD 8.99.34 (GENERIC) #12: Wed Feb  6 17:38:03 CET 2019  root@chieftec:/public/netbsd-root/sys/arch/amd64/compile/GENERIC amd64

* Host OS architecture: x86\_64
x86_64 (amd64)

* Host CPU model: 
N/A

* Host RAM size: 
N/A

* (Optional) Host computer model: 
N/A

**Guest Environment**
Any non-trivial guest such as NetBSD.

* Android Emulator or QEMU version: 
qemu used directly, no Android Emulator.

* Guest OS version: 
Any.

* Guest OS architecture: 
x86_64, i386 untested

**To Reproduce**
`qemu-system-x86_64 -accel hax`

1. build qemu with NetBSD host support patch
2. build haxm from original github sources (unmodified)
3. insert haxm.kmod into the kernel
4. qemu-system-x86_64 -accel hax `

**Expected Behavior**

Stop triggering the FPU DNA exception.

FreeBSD code says that FPU DNA can be triggered by "some" VM engines.

**Reproducibility**

Always

**Diagnostic Information**

Host crash dump: 

Not provided, I don't like to panic my host again to get the backtrace.

HAXM log: 

Not provided.

Android Emulator or QEMU log: 

N/A

Screenshots:
 
Not provided.

**Additional context**

Please see the comment in `%cr0.TS`:

```
/*
 * Device Not Available (DNA, #NM) exception handler.
 *
 * It would be better to switch FP context here (if curthread !=
 * fpcurthread) and not necessarily for every context switch, but it
 * is too hard to access foreign pcb's.
 */
void
fpudna(void)
{
	struct thread *td;

	td = curthread;
	/*
	 * This handler is entered with interrupts enabled, so context
	 * switches may occur before critical_enter() is executed.  If
	 * a context switch occurs, then when we regain control, our
	 * state will have been completely restored.  The CPU may
	 * change underneath us, but the only part of our context that
	 * lives in the CPU is CR0.TS and that will be "restored" by
	 * setting it on the new CPU.
	 */
	critical_enter();

	KASSERT((curpcb->pcb_flags & PCB_FPUNOSAVE) == 0,
	    ("fpudna while in fpu_kern_enter(FPU_KERN_NOCTX)"));
	if (__predict_false(PCPU_GET(fpcurthread) == td)) {
		/*
		 * Some virtual machines seems to set %cr0.TS at
		 * arbitrary moments.  Silently clear the TS bit
		 * regardless of the eager/lazy FPU context switch
		 * mode.
		 */
		stop_emulating();
	} else {
		if (__predict_false(PCPU_GET(fpcurthread) != NULL)) {
			panic(
		    "fpudna: fpcurthread = %p (%d), curthread = %p (%d)\n",
			    PCPU_GET(fpcurthread),
			    PCPU_GET(fpcurthread)->td_tid, td, td->td_tid);
		}
		restore_fpu_curthread(td);
	}
	critical_exit();
}
```

https://github.com/freebsd/freebsd/blob/master/sys/amd64/amd64/fpu.c#L699

`stop_emulating()` translates to `clts()`

Cherry-picking this to the NetBSD kernel workarounds the issue.

http://www.netbsd.org/~kamil/patch-00083-fpu-dna-netbsd8.txt

However this workaround has been rejected by the x86 NetBSD port maintainer and we are expected to address this in HAXM. Additionally fixing this in HAXM will allow to use older released versions as they are.

NVMM/NetBSD works without this workaround.

This workaround is the only patch needed for the NetBSD kernel in order to run HAXM. Likely all other mainstream OSes workaround this (Windows, Darwin, Linux, FreeBSD, OpenBSD), but it's still likely a generic bug.

**Comment by krytarowski** [comment]
Kernel backtrace of the FPU DNA crash.

```
[ 21166,199133] haxm_warning: -------- HAXM v7.3.2 Start --------
[ 21171,441312] haxm_warning: hax_alloc_pages: HAX_MEM_LOW_4G is ignored
[ 21172,501753] panic: fpudna from kernel, ip 0xffffffff81cb902f, trapframe 0xffffc9025c298ac0

[ 21172,501753] cpu6: Begin traceback...
[ 21172,501753] vpanic() at netbsd:vpanic+0x16f
[ 21172,501753] snprintf() at netbsd:snprintf
[ 21172,501753] fpu_set_default_cw() at netbsd:fpu_set_default_cw
[ 21172,501753] Xtrap07() at netbsd:Xtrap07+0xc2
[ 21172,501753] cpu_vmx_run() at haxm:cpu_vmx_run+0x27
[ 21172,501753] cpu_vmx_execute() at haxm:cpu_vmx_execute+0xad
[ 21172,501753] vcpu_execute() at haxm:vcpu_execute+0x96
[ 21172,501753] hax_vcpu_ioctl() at haxm:hax_vcpu_ioctl+0x1db
[ 21172,501753] cdev_ioctl() at netbsd:cdev_ioctl+0xc0
[ 21172,501753] VOP_IOCTL() at netbsd:VOP_IOCTL+0x54
[ 21172,501753] vn_ioctl() at netbsd:vn_ioctl+0xa1
[ 21172,501753] sys_ioctl() at netbsd:sys_ioctl+0x11c
[ 21172,501753] syscall() at netbsd:syscall+0x173
[ 21172,501753] --- syscall (number 54) ---
[ 21172,501753] 7f7ff270eb9a:
[ 21172,501753] cpu6: End traceback...
[ 21172,501753] fatal breakpoint trap in supervisor mode
[ 21172,501753] trap type 1 code 0 rip 0xffffffff8021de45 cs 0x8 rflags 0x2 cr2 0x7f7ff21ffff8 ilevel 0 rsp 0xffffc9025c2989f0
[ 21172,501753] curlwp 0xffffb81b8f0f64a0 pid 28400.5 lowest kstack 0xffffc9025c2952c0
```

**Comment by raphaelning** [comment]
Just curious, have you tried to disassemble the HAXM binary and figure out what instruction is at this address:

> [ 21172,501753] cpu_vmx_run() at haxm:cpu_vmx_run+0x27

I'd expect it to be FXSAVE or FXRSTOR, but I wonder why the stacktrace doesn't show the entire call hierarchy:

```
vcpu_enter_fpu_state()
vcpu_save_host_state()
cpu_vmx_run()
...
```

Hopefully it's just compiler optimization.

**Comment by krytarowski** [comment]
When I was looking at it originally, it was for FXSAVE/FXRSTOR. This is how I've navigated the issue to CR0_TS. I've already upgraded my host compiler (to GCC7) and new kernel.. so backtrace might not be accurate any more and I will resist panicking my host kernel again (if there would be support for nested virtualization and panicking guest it would be fine).

**Comment by raphaelning** [comment]
Cool, I was just double-checking.
