### ISSUE TITLE
Unable to build HAXM

### ISSUE THREAD

**Issue by leecher1337** [intel/haxm#169]
**Describe the Bug**

Unable to build HAXM with Visual studio 2017

> 2>------ Neues Erstellen gestartet: Projekt: haxm-windows, Konfiguration: Debug x64 ------
> 2>Building 'haxm-windows' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
> 2>MC: Compiling hax_event_win.mc
> 2>components.c
> 2>hax_entry.c
> 2>hax_event.c
> 2>hax_host_mem.c
> 2>hax_mem_alloc.c
> 2>hax_mm.c
> 2>hax_winlog.c
> 2>hax_wrapper.c
> 2>Code wird generiert...
> 2>BufferOverflowK.lib(loadcfg.obj) : error LNK2001: Nicht aufgelöstes externes Symbol "__dynamic_value_reloc_table".
> 2>C:\Users\ert\Documents\Visual Studio 2017\Projects\haxm-master\platforms\windows\build\out\x64\Debug\IntelHaxm.sys : fatal error LNK1120: 1 nicht aufgelöste Externe
> 2>Die Erstellung des Projekts "haxm-windows.vcxproj" ist abgeschlossen -- FEHLER.
> 
> ========== Alles neu erstellen: 1 erfolgreich, 1 fehlerhaft, 0 übersprungen ==========

Summary: 

**Host Environment**

* HAXM version: 7.4.1
* Host OS version: Windows 10 Pro version 1511 Build 10586.36
* Host OS architecture: x86\_64
* Host CPU model: Intel Xeon E31235
* Host RAM size: 12 GB

**To Reproduce**

1. Load .sln in Visual Studio 2017
2. Build haxm-windows project

**Expected Behavior**
It should compile and output .sys file

**Reproducibility**
100%

**Comment by leecher1337** [comment]
Seems I had to retarget SDK version to 10.0.10586.0, which doesn'T expose this problem, newer SDK versions seem to fail as described.

**Comment by raphaelning** [comment]
Interesting... Windows 10 version 1511 predates VS2017, and I've never tried that combination myself. Theoretically, the Windows 10 SDK version used for building HAXM doesn't have to match the host Windows 10 version. If you want to use a newer SDK version, maybe you could try a recent release of Enterprise WDK (EWDK) as the build environment, which is usually hassle-free.
