### ISSUE TITLE
Qemu 3.1 does not work with haxm

### ISSUE THREAD

**Issue by mifritscher** [intel/haxm#177]
Haxm 7.4.1 does not work with Qemu 3.1 (https://qemu.weilnetz.de/w64/qemu-w64-setup-20190218.exe) - the famous "VCPU shutdown request" on early boot...

Older Qemu does work.

Windows 7 64 bit + kernel/initrd from http://de.archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/netboot/netboot.tar.gz .

P.S. I thought I read something related here, but could not find it...

**Comment by raphaelning** [comment]
> P.S. I thought I read something related here, but could not find it...

Probably #171. So do you have `-smp` in your QEMU command line? If you filled out our bug report template, you would have provided this piece of information already :-)

**Comment by mifritscher** [comment]
Oh, sorry, yes, with -smp 2. Thanks for the pointer to the issue ;-)

Regarding the bug report template: Yesterday I managed to get to https://github.com/intel/haxm/issues/new directly, without going through https://github.com/intel/haxm/issues/new/choose . This way I got no template - and this is why I forgot the command line, which I'll dd when I'm at the work side again.

**Comment by raphaelning** [comment]
No worries, I can see the "New issue" button point to the correct link (`new/choose`), so just remember to use it next time :-)

If you confirm that your guest boots without `-smp 2`, I'll close this issue as a duplicate.

**Comment by mifritscher** [comment]
Yes, -smp 2 is the cullprit. More information in #171 ;)
