### ISSUE TITLE
Error 2755 when installing on Windows 10

### ISSUE THREAD

**Issue by zhaobenx** [intel/haxm#192]
**Installation failed and show 2755 error**

Summary: 
Error message:

![image](https://user-images.githubusercontent.com/23143530/53439162-71192e80-39cf-11e9-8754-4b81e39890c2.png)
After click cancel:
![image](https://user-images.githubusercontent.com/23143530/53439161-71192e80-39cf-11e9-91ed-71432bbfa3e2.png)

I have tried many solution online, including create c:\windows\installer( it exists before i created it); disable windows defender; disable hyperV; enable virtualization; adding system group to the exe(it is in system group before i did).
I tried downloading 7.4.1 from github release and the same issue.
I also extract the exe and install hax64/hax64_legacy.msi, the same issue happens(with admin privilege).
This error does not happen when I installing other software.

And this is a new computer, I didn't change much on system settings. 
**Host Environment**

* HAXM version: 7.3.2 and 7.4.1

* Host OS version: Windows 10 Pro version 1803

* Host OS architecture: x86\_64

* Host CPU model: i7-8850H

* Host RAM size: 16GB

* (Optional) Host computer model: Thinkpad X1 Extreme

**Guest Environment**

**To Reproduce**

1. 
2. 
3. 

**Expected Behavior**

Expectation: 

**Reproducibility**

**Diagnostic Information**

Host crash dump: 

HAXM log: 

Android Emulator or QEMU log: 

Screenshots: 

**Additional context**

None

**Comment by wcwang** [comment]
Could you please attach the installation and uninstallation logs for further analysis? These logs can be found at C:\Users\<account>\AppData\Local\Temp\. The filenames are formatted as haxm_install-<DATE>_<TIME>.log or haxm_uninstall-<DATE>_<TIME>.log. Thanks.

**Comment by zhaobenx** [comment]
This is log for the failed installation.
[haxm_install-20190227_1427.log](https://github.com/intel/haxm/files/2911981/haxm_install-20190227_1427.log)

But after I first enabled and then disabled hyper V, I found that I can install this software. But I don't know why.

**Comment by cybermerlin** [comment]
TPM system was block some operation for non trusted certificate sign
