### ISSUE TITLE
Android studio emulator is not working with Core i3 and showing multiple errors

### ISSUE THREAD

**Issue by abddi** [intel/haxm#196]
Hey everyone hope you're doing good,
Recently i have update android studio to the latest version and tried to run the emulator but it does not work!
My desktop hardware has an intel core i3 cpu and 8g of Rams working on windows 10.
Here is the bug:
3/23/2019
5:14 PM	Emulator: Warning: Quick Boot / Snapshots not supported on this machine. A CPU with EPT + UG features is currently needed. We will address this in a future release.

5:14 PM	Emulator: dsound: Could not initialize DirectSoundCapture

5:14 PM	Emulator: dsound: Reason: No sound driver is available for use, or the given GUID is not a valid DirectSound device ID

5:14 PM	Emulator: dsound: Attempt to initialize voice without DirectSoundCapture object

5:14 PM	Emulator: dsound: Attempt to initialize voice without DirectSoundCapture object

5:14 PM	Emulator: audio: Failed to create voice `goldfish_audio_in'

5:14 PM	Emulator: C:\USERS\AppData\Local\Android\Sdk\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: warnin

5:14 PM	Emulator: g: opening audio input failed

5:14 PM	Emulator: dsound: Attempt to initialize voice without DirectSoundCapture object

5:14 PM	Emulator: dsound: Attempt to initialize voice without DirectSoundCapture object

5:14 PM	Emulator: audio: Failed to create voice `adc'

5:14 PM	Emulator: FB::flushWindowSurfaceColorBuffer: window handle

5:14 PM	Emulator: 0x9 not found

5:18 PM	Emulator: deleteSnapshot: for default_boot

5:18 PM	Emulator: Process finished with exit code 0

**Comment by HaHoYou** [comment]
Would you get log on Windows, https://github.com/intel/haxm/blob/master/docs/manual-windows.md#capturing-driver-logs , and what is your emulator and HAXM version? You could get the emulator version in Android Studio. And get HAXM 's in Settings\Apps & Features.
