### ISSUE TITLE
Can't insall HAXM

### ISSUE THREAD

**Issue by allenchann** [intel/haxm#202]
My OS is macOS 10.14.4
And the HAXM version is Version 7.3.2

**Comment by HaHoYou** [comment]
See https://github.com/intel/haxm/wiki/Installation-Instructions-on-macOS -> ‘Allowing HAXM to run on macOS High Sierra (10.13) and Mojave (10.14)’

**Comment by allenchann** [comment]
![image](https://user-images.githubusercontent.com/16041349/56644989-5f8e9300-66af-11e9-9f62-e301d7a5f26e.png)
It had some trouble when i run 'sudo kextunload –b com.intel.kext.intelhaxm'.
And I cannot find the system image when i create a device
![image](https://user-images.githubusercontent.com/16041349/56645082-906ec800-66af-11e9-80a9-0f58841c0fde.png)

**Comment by HaHoYou** [comment]
For the 1st question, maybe you do not installed successfully in the 1st place, you could check whether installed with command 'kextstat |grep intel'
For the 2nd question, it is not Intel's issue. However, it probably because that it has not download the 'Android SDK Platform xx', besides 'System image'. You could download in Sdk Manager.

**Comment by allenchann** [comment]
![image](https://user-images.githubusercontent.com/16041349/56711581-f9147e00-675d-11e9-850c-9e08803ca6ea.png)
I try to run 'sudo HAXM\ installation -u'.And it has problem like this"sudo: HAXM installation: command not found"

**Comment by HaHoYou** [comment]
The file"HAXM installation" was there, see your 1st Picture, but which you have already removed? Also, you may download and unzip to get it from our release page.

**Comment by wayne-ma** [comment]
@allenchann , Could you install haxm on your Mac machine now? If yes, I will close the issue here.
