### ISSUE TITLE
Whre to get latest build?

### ISSUE THREAD

**Issue by delfer** [intel/haxm#21]
On main page https://software.intel.com/en-us/articles/intel-hardware-accelerated-execution-manager-intel-haxm it is only version 6.1.1.
https://github.com/intel/haxm/releases is empty.
Where to get latest build? 7.0.0 for now.

**Comment by HaHoYou** [comment]
It will release soon, in a week. Or, you can build from latest code in git if in a hurry.

**Comment by wcwang** [comment]
The latest build of HAXM v7.0.0 will be released on https://software.intel.com/en-us/articles/intel-hardware-accelerated-execution-manager-intel-haxm in a week. Currently the official release is 6.2.1. The previous answer was from Intel QA team and the update task is on progress.

**Comment by wcwang** [comment]
HAXM v7.0.0 release packages have been uploaded in GitHub. You can find them under the release tab. Furthermore, the subsequent release packages will be also posted to GitHub.

**Comment by delfer** [comment]
@wcwang Thank you!
