### ISSUE TITLE
can the HAXM working on "AMD FX-6300 Six-Core" CPU ?

### ISSUE THREAD

**Issue by vesaldivan** [intel/haxm#212]
my CPU is "[AMD FX-6300 Six-Core](https://www.cpubenchmark.net/cpu.php?cpu=AMD+FX-6300+Six-Core&id=1781)" , im an Android devloper.
can anyone check that is working HAXM on my sysyem or no ?

[this image of my CPU VT technology](http://s4.picofile.com/file/8363708300/Capture.PNG)

Thank you so much

**Comment by wayne-ma** [comment]
Hi @vesaldivan ,AMD cpu is not supported so far. Please use the Intel CPU and try again, make sure to enable VT .

**Comment by mirh** [comment]
There is a tentative branch trying to get AMD-V working
https://github.com/jarveson/haxm/tree/svm
