### ISSUE TITLE
Can't install HAXM on macOS, as "Intel Corporation Apps" developer certificate has expired

### ISSUE THREAD

**Issue by shirakaba** [intel/haxm#219]
**Describe the Bug**

Both silent and non-silent installs of HAXM fail on macOS.

Silent install:

```sh
$ ~/Library/Android/sdk/extras/intel/Hardware_Accelerated_Execution_Manager/silent_install.sh
# Fails, telling me to inspect the logs
$ cat /private/tmp/haxm_silent_run.log
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	Apple_HFS                      	/Volumes/com_intel_kext_haxm_disc
mpkg_file=/Volumes/com_intel_kext_haxm_disc//IntelHAXM_7.3.2.mpkg
ecx 7ffafbff
edx 2c100800
edx 2c100800
No emulator instance exist!
sed: /Library/Extensions/intelhaxm.kext/Contents/Resources/support.txt: No such file or directory
Intel HAXM: This is a new installation
installer: Package name is Intel(R) Hardware Accelerated Execution Manager
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
"disk3" ejected.
Error: The installation-check script run failed ! 
*************** Silent installation failed ! ****************
```

Non-silent install, by running the `.pkg` installer provided by mounting `~/Library/Android/sdk/extras/intel/Hardware_Accelerated_Execution_Manager/IntelHAXM_7.3.2.dmg`:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/14055146/60767617-56a83d80-a0b2-11e9-8725-0c257fe9d622.png">

So Intel needs to renew the certificate, as it expired a couple of weeks ago.

**Host Environment**

* HAXM version: 7.3.2
* Host OS version: macOS 10.14.5
* Host OS architecture: x86\_64
* Host CPU model: 2.3 GHz Intel Core i5
* Host RAM size: 16 GB

**Guest Environment**

N/A

**To Reproduce**

Reproduction steps given above. Basically just try to install HAXM on macOS.

**Expected Behavior**

Expectation: Certificates should be in-date and thus installation should succeed.

**Reproducibility**

100%, for now!

**Diagnostic Information**

See above.

**Additional Information**

I am aware that I could install it by trusting the expired certificate or appending `-allowUntrusted`, but I refuse, as it's a security risk.

**Comment by retokromer** [comment]
lol

**Comment by wayne-ma** [comment]
@shirakaba , thanks for reporting this issue. There was indeed a certificate compatibility issue with new Mac OS version, and we resolved with the latest HAXM release. Could you try the latest HAXM verison v7.5.1, which could be downloaded from the release page. https://github.com/intel/haxm/releases ?

**Comment by shirakaba** [comment]
Hi @wayne-ma, I successfully installed it this time; the certificates were fine. I'll have to restart my computer before I can assess whether the installed package works, but I can at least confirm that the certificates issue is resolved. Thanks for sorting it out!

**Comment by pcstory** [comment]
→ cat /private/tmp/haxm_silent_run.log
/dev/disk6          	GUID_partition_scheme
/dev/disk6s1        	Apple_HFS                      	/Volumes/com_intel_kext_haxm_disc
mpkg_file=/Volumes/com_intel_kext_haxm_disc//IntelHAXM_7.3.2.mpkg
ecx 7ffafbff
edx 2c100800
edx 2c100800
No emulator instance exist!
haxm-isDowngrade: installed version of Intel HAXM found = 7.3.2; current version = 7.3.2
current version is the same or newer than existing one
Intel HAXM: This is a re-installation (chnage of memory limit)
installer: Warning - Intel Hardware Accelerated Execution Manager is already installed on this computer. If you continue installation, the Intel HAXM will be re-installed.
installer: Package name is Intel(R) Hardware Accelerated Execution Manager
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
"disk6" ejected.
Error: The installation-check script run failed !
*************** Silent installation failed ! ****************
