### ISSUE TITLE
SurfacePro4, W10 version 1903 (OS Build 18362.239) - blue screen

### ISSUE THREAD

**Issue by anthonylamark** [intel/haxm#221]
“Android Virtual Device” (AVD) instance crashed (blue screened) the SurfacePro4, W10 version 1903 (OS Build 18362.239):

BugCheck A, {39cafc88, ff, a6, fffff8002d645a32}

*** ERROR: Module load completed but symbols could not be loaded for IntelHaxm.sys
Probably caused by : IntelHaxm.sys ( IntelHaxm+28a8 )

*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

IRQL_NOT_LESS_OR_EQUAL (a)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If a kernel debugger is available get the stack backtrace.
Arguments:
Arg1: 0000000039cafc88, memory referenced
Arg2: 00000000000000ff, IRQL
Arg3: 00000000000000a6, bitfield :
	bit 0 : value 0 = read operation, 1 = write operation
	bit 3 : value 0 = not an execute operation, 1 = execute operation (only on chips which support this level of status)
Arg4: fffff8002d645a32, address which referenced memory

Debugging Details:
------------------

DUMP_CLASS: 1

DUMP_QUALIFIER: 401

BUILD_VERSION_STRING:  18362.1.amd64fre.19h1_release.190318-1202

SYSTEM_MANUFACTURER:  Microsoft Corporation

SYSTEM_PRODUCT_NAME:  Surface Pro 4

SYSTEM_SKU:  Surface_Pro_4

SYSTEM_VERSION:  D:0B:08F:1C:03P:38

BIOS_VENDOR:  Microsoft Corporation

BIOS_VERSION:  108.2706.768

BIOS_DATE:  04/18/2019

BASEBOARD_MANUFACTURER:  Microsoft Corporation

BASEBOARD_PRODUCT:  Surface Pro 4

DUMP_TYPE:  1

BUGCHECK_P1: 39cafc88

BUGCHECK_P2: ff

BUGCHECK_P3: a6

BUGCHECK_P4: fffff8002d645a32

READ_ADDRESS: Unable to get offset of nt!_MI_VISIBLE_STATE.SpecialPool
Unable to get value of nt!_MI_VISIBLE_STATE.SessionSpecialPool
 0000000039cafc88 

CURRENT_IRQL:  1

FAULTING_IP: 
nt!IopCompleteRequest+f2
fffff800`2d645a32 48894108        mov     qword ptr [rcx+8],rax

CPU_COUNT: 4

CPU_MHZ: 8a0

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 4e

CPU_STEPPING: 3

CPU_MICROCODE: 6,4e,3,0 (F,M,S,R)  SIG: CC'00000000 (cache) CC'00000000 (init)

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

BUGCHECK_STR:  AV

PROCESS_NAME:  qemu-system-x86_64.exe

ANALYSIS_SESSION_HOST:  SURFACEPRO4

ANALYSIS_SESSION_TIME:  07-13-2019 11:21:04.0205

ANALYSIS_VERSION: 10.0.15063.468 amd64fre

IRP_ADDRESS: ffffffffffffff88

TRAP_FRAME:  fffffe8fbf55f160 -- (.trap 0xfffffe8fbf55f160)
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect.
rax=0000000000000000 rbx=0000000000000000 rcx=0000000039cafc80
rdx=fffffe8fbf55f420 rsi=0000000000000000 rdi=0000000000000000
rip=fffff8002d645a32 rsp=fffffe8fbf55f2f0 rbp=fffffe8fbf55f439
 r8=fffffe8fbf55f438  r9=fffffe8fbf55f430 r10=fffff8002d645940
r11=0000000000000000 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up di pl zr na po nc
nt!IopCompleteRequest+0xf2:
fffff800`2d645a32 48894108        mov     qword ptr [rcx+8],rax ds:00000000`39cafc88=????????????????
Resetting default scope

LAST_CONTROL_TRANSFER:  from fffff8002d7ce6e9 to fffff8002d7bc900

STACK_TEXT:  
fffffe8f`bf55f018 fffff800`2d7ce6e9 : 00000000`0000000a 00000000`39cafc88 00000000`000000ff 00000000`000000a6 : nt!KeBugCheckEx
fffffe8f`bf55f020 fffff800`2d7caa2b : 00000000`00000000 00000000`00000000 00000000`00000000 fffff800`49a03156 : nt!KiBugCheckDispatch+0x69
fffffe8f`bf55f160 fffff800`2d645a32 : ffff908f`869cb920 00000000`00000000 00000000`3a231000 00000000`ba221000 : nt!KiPageFault+0x46b
fffffe8f`bf55f2f0 fffff800`2d63d72d : 00000000`00000000 ffff908f`803cc080 ffff908f`99892500 ffff908f`99892470 : nt!IopCompleteRequest+0xf2
fffffe8f`bf55f3e0 fffff800`2d6480f2 : ffffffff`00000000 00000000`00000000 ffff908f`00000000 00000000`00000000 : nt!KiDeliverApc+0x19d
fffffe8f`bf55f4a0 fffff800`2d64709b : ffff908f`803cc080 ff8918e3`c1f3720c ffff908f`803cc080 ffff9198`1229ec0e : nt!KiExitDispatcher+0x282
fffffe8f`bf55f500 fffff800`2d646b67 : 00000000`00000000 7fff908f`79d64800 00000000`00000000 00000000`00000000 : nt!IopfCompleteRequest+0x51b
fffffe8f`bf55f610 fffff800`49a028a8 : 00000000`00000000 ffff908f`79d66010 ffff908f`88ced500 00000000`00000000 : nt!IofCompleteRequest+0x17
fffffe8f`bf55f640 fffff800`49a0250f : ffff908f`88ced430 fffffe8f`bf55f700 ffff908f`99892470 ffff908f`99892470 : IntelHaxm+0x28a8
fffffe8f`bf55f6d0 fffff800`2d631cc9 : ffff908f`99892470 00000000`00000000 00000000`40002418 00000000`00000001 : IntelHaxm+0x250f
fffffe8f`bf55f700 fffff800`2dbeb6c5 : fffffe8f`bf55fa80 ffff908f`88ced430 00000000`00000001 ffff908f`99892470 : nt!IofCallDriver+0x59
fffffe8f`bf55f740 fffff800`2dbeb01a : ffff908f`00000000 00000000`40002418 00000000`00000000 fffffe8f`bf55fa80 : nt!IopSynchronousServiceTail+0x1a5
fffffe8f`bf55f7e0 fffff800`2dbeaa36 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!IopXxxControlFile+0x5ca
fffffe8f`bf55f920 fffff800`2d7ce115 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!NtDeviceIoControlFile+0x56
fffffe8f`bf55f990 00007ffb`33fbc144 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x25
00000000`39cafc28 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007ffb`33fbc144

STACK_COMMAND:  kb

THREAD_SHA1_HASH_MOD_FUNC:  965fa368e0280ed957bb788db67bc2bcdc17ff3f

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  62b4fd1f488db681851b3385e925771262e326f1

THREAD_SHA1_HASH_MOD:  52d93e4427b781f23e55209e8f4885af6b101c56

FOLLOWUP_IP: 
IntelHaxm+28a8
fffff800`49a028a8 4885ed          test    rbp,rbp

FAULT_INSTR_CODE:  74ed8548

SYMBOL_STACK_INDEX:  8

SYMBOL_NAME:  IntelHaxm+28a8

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: IntelHaxm

IMAGE_NAME:  IntelHaxm.sys

DEBUG_FLR_IMAGE_TIMESTAMP:  5cb6c325

BUCKET_ID_FUNC_OFFSET:  28a8

FAILURE_BUCKET_ID:  AV_CODE_AV_IntelHaxm!unknown_function

BUCKET_ID:  AV_CODE_AV_IntelHaxm!unknown_function

PRIMARY_PROBLEM_CLASS:  AV_CODE_AV_IntelHaxm!unknown_function

TARGET_TIME:  2019-07-12T15:53:27.000Z

OSBUILD:  18362

OSSERVICEPACK:  0

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  272

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  1972-02-02 00:33:06

BUILDDATESTAMP_STR:  190318-1202

BUILDLAB_STR:  19h1_release

BUILDOSVER_STR:  10.0.18362.1.amd64fre.19h1_release.190318-1202

ANALYSIS_SESSION_ELAPSED_TIME:  7f3

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:av_code_av_intelhaxm!unknown_function

FAILURE_ID_HASH:  {6dde09c0-a81a-6bff-e068-83d929a10c64}

Followup:     MachineOwner
---------

**Comment by coxuintel** [comment]
Sorry for the inconvenience. We have root caused the issue and mixed it by commit de01cbad907273ac69140387d424175050fdbc32. If you may compile the test driver you could have a quick try. 
We will drop next release soon which contains the fix.

**Comment by TWiStErRob** [comment]
@anthonylamark how did you get that dump? I have a BSOD, that now repeated twice, but don't know how to capture info.

**Comment by Mianpier** [comment]
Could you help to find the minidump files in C:\Windows\Minidump\ and the full memory dump in C:\Windows\MEMORY.dmp

**Comment by coxuintel** [comment]
Try v7.5.4 if you hit BSOD IRQL_NOT_LESS_OR_EQUAL. We fixed an issue which may report the same BSOD code, see if it can fix yours.
