### ISSUE TITLE
"HAXM can't work on system without VT support

### ISSUE THREAD

**Issue by makedir** [intel/haxm#226]
I just noticed 3 errors everytime booting my Dell XPS 15 9570 laptop, connected to Intel HAXM:

HAXM can't work on system without VT support
HAXM Failed to init VMX
Der Dienst "IntelHaxm" wurde aufgrund folgenden Fehlers nicht gestartet: 
Ein an das System angeschlossenes Gerät funktioniert nicht.

Whats this about? The installed version is 7.3.0 from Dell site. Windows 10 1903.

**Comment by wayne-ma** [comment]
Hi, HAXM requires an Intel processor with Intel VT-x functionality and cannot be used on systems lacking this hardware feature. You can check your hardware status by follow this [instruction ](https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows). If your computer supports VT technology ,you can enable it by the instruction then try the HAXM again. 
BTW, we strongly suggest you to use the latest release version HAXM v7.5.2.

**Comment by makedir** [comment]
> VT-x

Like I said, it is a Dell XPS 15 9570 laptop, which has an Intel i7-8750H CPU, which obviously supports VT-x.

https://ark.intel.com/content/www/us/en/ark/products/134906/intel-core-i7-8750h-processor-9m-cache-up-to-4-10-ghz.html

@wayne-ma

**Comment by wayne-ma** [comment]
Hi, it is weird here. Generally, the HAXM could be installed if you enabled VT and disabled Hyper-V related option. Did you enable/use Sand box or Windows Hypervisor Platform or WSL2 feature ? These 3 features also conflict with HAXM , could you confirm the status on your Windows 10 system? You can also refer to the"One-time setup" and "Disabling Hyper-V on Windows 10" chapters in [HAXM instruction](https://github.com/intel/haxm/blob/master/docs/manual-windows.md) for windows

**Comment by makedir** [comment]
I have fixed it, after I read a hint here: https://www.reddit.com/r/Dell/comments/4eac0h/psa_how_i_got_vtx_working_on_my_dell_xps_9550/

This seems like a nasty bios bug since 3 egenerations now, for the Dell XPS 15 series. So it mostly is happening for XPS 15 9550 9560 and my 9570 too.

There is just an option in bios "VT enable" which was on. Toggling it off rebooting into Windows, task manager said vt is off, toggling it on, task manager said vt was on, but HAXM still reported VT-x was off.

I used Intel ident tool and it reported: https://i.imgur.com/zlqtJys.png even Windows 10 task manager reported VT was on.

I then did the entire thing suggested in the reddit post, reset all bios settings to default, toggle vt off on again, rebooted, and NOW Intel tool reported: https://i.imgur.com/WM0q2fC.png

Seems Dell is incompetent, and hide the options for vt-x and maybe some more, and those arent on per default even if you toggle VT on in bios, which is the only option, a normal user can see.

**Comment by wayne-ma** [comment]
Great, good to know you have fixed it, seems it is related to Dell Bios. So if no more HAXM installation issue here I will close this issue.

**Comment by Zapnologica** [comment]
I am having the same issued on windows 10 desktop with i9 cpu.  haxm errors in the windows event viewer, pc just goes black and reboots.

**Comment by xpsdeset** [comment]
@Zapnologica  same here not sure what's going on.

**Comment by wayne-ma** [comment]
> I am having the same issued on windows 10 desktop with i9 cpu. haxm errors in the windows event viewer, pc just goes black and reboots.

Could you raise a new issue as this one is closed? More details are appreciated.

**Comment by wayne-ma** [comment]
> @Zapnologica same here not sure what's going on.

Please also open a new issue with details, thx.

**Comment by xpsdeset** [comment]
I believe disabling Disable Hyper-V solves it. 
@Zapnologica  

Refer https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/virtualization-apps-not-work-with-hyper-v

And see if it makes any difference.

**Comment by siguy85** [comment]
I had a similar issue on Lenovo Thinkbook... I followed the tips here https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows#tips-and-tricks - i think the part that fixed it was:

Open an elevated (i.e. Run as administrator) Command Prompt.
Run `bcdedit /set hypervisorlaunchtype off`
