### ISSUE TITLE
Invalid digital signature in HAXM 7.5.2

### ISSUE THREAD

**Issue by intxx0** [intel/haxm#227]
Hi,

After intalled Intel HAXM 7.5.2, the Windows 7 x64 not accept digital signature. It was updated to this version in Android Studio 3.4. Is the same problem in https://github.com/intel/haxm/issues/56

Any way to solve this?

**Comment by HaHoYou** [comment]
This should not be a issue, if you installed v7.5.1 successfully. Because in release note https://github.com/intel/haxm/releases, 7.5.2 has to drop SHA-1 after Microsoft update the signing tool. And I think your windows 7 version is SP1. see https://github.com/intel/haxm/wiki/Known-Issues.

**Comment by arooshaa17** [comment]
I have tried all of the following options but it did not work. Can anyone help me?
- Removed all unused programs and viruses or antiviruses from windows. 
- Installed previous versions of HAXM 7.3.2 rebooted
- Enabled Virtualization technology(VT-X) from BIOS
- Installed HAXM from Intel website, a github link for all releases
- Downloaded haxm-extract-workaround from intel forum and tried with it.
- Updated Windows Security patch
- Downgraded to Digitally signed version of Haxm 7.1.0
- Enabled Extened bit option from CPU performance
- Installed haxm from SDK->Extras directory. It was in directory like sdk\extras\intel\Hardware_Accelerated_Execution_Manager - install it by running its package from the directory.
My CPU is Intel Core i5 4200U which supports Virtualization VT-x and Execute bit option.

**Comment by IYJan** [comment]
> I have tried all of the following options but it did not work. Can anyone help me?
> 
> * Removed all unused programs and viruses or antiviruses from windows.
> * Installed previous versions of HAXM 7.3.2 rebooted
> * Enabled Virtualization technology(VT-X) from BIOS
> * Installed HAXM from Intel website, a github link for all releases
> * Downloaded haxm-extract-workaround from intel forum and tried with it.
> * Updated Windows Security patch
> * Downgraded to Digitally signed version of Haxm 7.1.0
> * Enabled Extened bit option from CPU performance
> * Installed haxm from SDK->Extras directory. It was in directory like sdk\extras\intel\Hardware_Accelerated_Execution_Manager - install it by running its package from the directory.
>   My CPU is Intel Core i5 4200U which supports Virtualization VT-x and Execute bit option.

Did u get this problem?
