### ISSUE TITLE
Cannot install HAXM, claiming HyperV is on or computer does not support it

### ISSUE THREAD

**Issue by locked-fg** [intel/haxm#241]
**Describe the Bug**

I cannot install HAXM any more on my computer any more (it did so successfully in the past!!).
It keeps telling me:
 

> Failed to install Intel HAXM. For details, please check the installation log: "F:\Temp\cache\haxm_log24665.txt"
> HAXM installation failed. To install HAXM follow the instructions found at: https://software.intel.com/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-windows
> Installer log is located at F:\Temp\cache\haxm_log24665.txt
> Installer log contents:
> === Logging started: 27.10.2019  20:42:38 ===
> This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed.
> Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information

 

My System:
Core i7 870 CPU @ 2.93GHz ( https://ark.intel.com/content/www/de/de/ark/products/41315/intel-core-i7-870-processor-8m-cache-2-93-ghz.html ) with virtualization being available due to the SPECs
Windows 10 Pro 1903 Build 18362.418
Hyper-V : off
Linux Subsystem for Windows: off
Windows-Hypervisor-Plattform: off
Bios: Virtualization enabled

The Intel processor identification program tells me that this CPU does NOT support "Intel Virtualization"(?!?)

Summary: 
HAXM refuses to install

**Host Environment**
* HAXM version: tried HAXM versions 7.5.2 - 7.4.1
* Host OS version: Windows 10 Pro 1903 Build 18362.418
* Host OS architecture: x86\_64
* Host CPU model: Core i7 870 CPU @ 2.93GHz 
* Host RAM size: 24GB

**Guest Environment**
* Android Emulator in Android Studio v3.5.1
* Guest OS version: HAXM doesn't even install

**To Reproduce**

**Expected Behavior**
HAXM installs

**Reproducibility**
100%

**Diagnostic Information**
HAXM log: 
=== Logging started: 27.10.2019  20:42:38 ===
This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed. 
Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information.

=== Logging stopped: 27.10.2019  20:42:38 ===

**Comment by HaHoYou** [comment]
It did so successfully in the past! Then what changed? You already tried old HAXM, then I guess it must be caused by Windows updated, Please check https://github.com/intel/haxm/issues/207 ( Cannot Install HAXM (7.5.1) in Windows 10 1903 #207) for resolution. And let me know if it works.

**Comment by locked-fg** [comment]
Hah! Finally I found it: Windows Defender Application guard needs to be disabled **as  well** (as it isolates [MS Edge into Hyper-V Containers](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/reqs-wd-app-guard). (Feels bad to disable security features)

Hyper-V was disabled, ```systeminfo.exe``` still showed ```a Hypervisor is detected```. Even though ```bcdeit``` (in powershell) showed ```hypervisorlaunchtype    Off```

**Comment by akrohn** [comment]
This didn't help for me. Did all this but still "a hypervisor is detected". I had to disable **Containers** in Windows Features and then it all went well.

**Comment by XertroV** [comment]
It might seem obvious in hindsight, but for anyone else finding their way here from google with an AMD CPU, HAXM isn't compatible (though the installer doesn't report this). See this Android Studio blog post about the alternative: <https://androidstudio.googleblog.com/2019/12/emulator-29211-and-amd-hypervisor-12-to.html>

**Comment by mg9101** [comment]
> It might seem obvious in hindsight, but for anyone else finding their way here from google with an AMD CPU, HAXM isn't compatible (though the installer doesn't report this). See this Android Studio blog post about the alternative: https://androidstudio.googleblog.com/2019/12/emulator-29211-and-amd-hypervisor-12-to.html
> 
> I also found #207 via google.

Thanks!! I couldn't find this anywhere

**Comment by amayzinone** [comment]
> It might seem obvious in hindsight, but for anyone else finding their way here from google with an AMD CPU, HAXM isn't compatible (though the installer doesn't report this). See this Android Studio blog post about the alternative: https://androidstudio.googleblog.com/2019/12/emulator-29211-and-amd-hypervisor-12-to.html
> 
> I also found #207 via google.

Wow, thank you.

**Comment by ahmedaniss25** [comment]
i fix this problem here : https://www.youtube.com/watch?v=KRmd2sUxI98

**Comment by mawais1078** [comment]
![Screenshot (179)](https://user-images.githubusercontent.com/54217042/116193856-6f7f5880-a749-11eb-96a5-63b571dfc00d.png)

what its mean?
