### ISSUE TITLE
Unable to boot ubuntu cloud-image with HAX enabled.

### ISSUE THREAD

**Issue by mdepa** [intel/haxm#249]
I'm trying to load Ubuntu bionic cloud image with QEmu and HAX acceleration. 
Usually the image loads correctly, while once HAX is enabled the boot hangs without any details.

**QEMU version:** v4.1.0-11789-g013a2ecf4f-dirty
**QEMU command line:** qemu-system-x86_64  -d guest_errors -m 1024 -drive file=cloud_image.qcow2,if=virtio  -no-acpi -no-hpet -display gtk  -boot c -drive file=cloud-init.iso,media=cdrom  -serial stdio -machine accel=hax
**OS Host:** Windows 10 64bit : Hyper-V disabled (VT support -- yes; NX support -- yes)
**OS Guest:** Linux 4.15.0-72-generic #81-Ubuntu x86_64

On output I just see: "`HAX is working and emulator runs in fast virt mode.`" and nothing more.

**Comment by wayne-ma** [comment]
@mdepa ,thanks for reporting the issue.We just verified the ubuntu generic 16.04 LTS version, it can boot up successfully. Could you try other versions of ubuntu image for bisect purpose?Or share us your haxm version, Ubuntu image/iso/qcow2 file? Thanks.

**Comment by mdepa** [comment]
Ciao  @wayne-ma, 

I confirm your experience: I've switched to **using the xenial image** and **it works**.
I've tested both xenial images: 

- xenial-server-cloudimg-amd64-disk1.img 
- xenial-server-cloudimg-amd64-uefi1.img 

The offending bionic image is: 

https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img

**Comment by wayne-ma** [comment]
Hi @mdepa ,we just verified your shared bionic cloud image with haxm. It also can boot up to the login window. Could you double confirm and wait for more time when launching the ubuntu guest?
Cmd line for your reference,
'qemu-system-x86_64 -d guest_errors -m 1024 -drive file=C:\Users\sdkot\Downloads\bionic-server-cloudimg-amd64.img,if=virtio -no-acpi -no-hpet -display gtk -boot c -drive file=C:\HAXM\qemu\temp\user-data.img,media=cdrom -serial stdio -machine accel=hax '
![launchubucloud](https://user-images.githubusercontent.com/8055260/70588165-d2308c80-1c06-11ea-81bd-55e34f03d355.png)

**Comment by mdepa** [comment]
Ciao @wayne-ma , 

unfortunately I confirm the behaviour: I've tested my original image dated 06122019 and also the most recent ones dated 09122019 and 11122019 and in all cases the execution hangs immediately after  "HAX is working and emulator runs in fast virt mode.".

Reverting the system back to using xenial solve the issue.

**Comment by wayne-ma** [comment]
@mdepa ,Good to know the xenial version solve the issue.So is it still a blocker for you now?If not, i will close this issue later.

**Comment by mdepa** [comment]
Well, I'd like to use the bionic cloud-image 'cause kubernetes and docker are better integrated.
Actually to use xenial I've to hack the cloud-init user data scripts.

Anyhow it's not blocking.

If you'd like to investigate why the hax hang I'm always available to experiment with it.

**Comment by wayne-ma** [comment]
Hi @mdepa ,we double checked the cloud image, it did boot up successfully on our side. So i wonder could you try again with the image&cmd i provided above ,or share us your cloud image including the init image you used.

**Comment by wayne-ma** [comment]
Hi @mdepa ,we double checked the cloud image, it did boot up successfully on our side. So i wonder could you try again with the image&cmd i provided above ,or share us your cloud image including the init image you used.

**Comment by wayne-ma** [comment]
Close the issue here as the Ubuntu cloud-image could bootup with HAXM.
