### ISSUE TITLE
/dev/kvm not found on OSX 

### ISSUE THREAD

**Issue by arthurdarcet** [intel/haxm#253]
**Describe the Bug**

Summary: I've installed the haxm kext on OSX, and the kernel module appears to be loaded, but `/dev/kvm` still does not exist.

**Host Environment**
* HAXM version: 7.4.5
* Host OS version: macOS 10.14.5
* Host OS architecture: x86\_64
* Host CPU model: Intel Core i7
* Host RAM size: 16GB
* (Optional) Host computer model: MacBookPro15,1

**Guest Environment**
Trying to run `ls /dev/kvm` - ultimately to run an Android Emulator through https://github.com/google/android-emulator-container-scripts

**Expected Behavior**
I would expect `/dev/kvm` to exist

**Diagnostic Information**

I'm checking that the kernel extension is loaded by running
```
% kextstat | grep intel
  192    0 0xffffff7f8429a000 0x28000    0x28000    com.intel.kext.intelhaxm (7.5.4) E622291F-7B94-3EA7-B644-97F1AD6DF807 <8 6 5 3 1>
```

HAXM log: 
```
 % log show --predicate 'sender == "intelhaxm"' --style syslog --last 5m
Filtering the log data using "sender == "intelhaxm""
Skipping info and debug messages, pass --info and/or --debug to include.
Timestamp                       (process)[PID]
2019-12-17 14:35:16.364229+0100  localhost kernel[0]: (intelhaxm) haxm_warning:
2019-12-17 14:35:16.364232+0100  localhost kernel[0]: (intelhaxm) -------- HAXM v7.5.4 End --------
2019-12-17 14:35:40.530580+0100  localhost kernel[0]: (intelhaxm) possible map ffffffffffffffff cpu_online_map fff
2019-12-17 14:35:40.530775+0100  localhost kernel[0]: (intelhaxm) haxm_warning:
2019-12-17 14:35:40.530777+0100  localhost kernel[0]: (intelhaxm) -------- HAXM v7.5.4 Start --------
```

**Additional context**
None

**Comment by wayne-ma** [comment]
Hi @arthurdarcet , HAXM is different with KVM. I noticed that you installed the HAXM successfully on your Mac Host but searched another hypervisor KVM. You can try to use HAXM  for acceleration or install KVM separately.
