### ISSUE TITLE
Cannot Install Manually or through Sdk Manager

### ISSUE THREAD

**Issue by Phred7** [intel/haxm#254]
Whenever I attempt to install haxm I get an error. Ive looked through many forums and q&a sites saying how to fix problems but I still cannot get it to install.

Ive tried multiple times through android studio and always get the same error (attached)
![Haxm](https://user-images.githubusercontent.com/10716448/71314836-738cbf00-240d-11ea-8737-b18bfd62382a.JPG)

Alternatively, I have downloaded the zip file from git hub but it doesn't contain any sort of installer like the documentation suggests.

Furthermore, I cannot see Hyper-V in the programs and features section of the control panel, my computer has virtualization enabled and Im running windows 10 on a i7-8750H

Please let me know what I am doing wrong

**Comment by wayne-ma** [comment]
@Phred7 ,could you try to download and install the release version from below link?
https://github.com/intel/haxm/releases/download/v7.5.4/haxm-windows_v7_5_4.zip

**Comment by Phred7** [comment]
Thank you, I thought I downloaded the installer before but I'm not sure what I did before because that worked flawlessly!

**Comment by wayne-ma** [comment]
Hi @Phred7 , so per my understanding ,you could install the HAXM v7.5.4 successfully now ,right? If so, I will close this issue here.
