### ISSUE TITLE
problem in stalling HAXM

### ISSUE THREAD

**Issue by shahbazgondal** [intel/haxm#262]
gentleman, Actually i am installing Android studio for flutter, so i have to install HAXM.
but there is some problem in installing it...
i am sending you pic please check it and help me as soon as possible.
i will be very thank full to you...
![IMG20200203222935](https://user-images.githubusercontent.com/60620948/73677962-2d4ba080-46d9-11ea-83f2-45e1c99c049f.jpg)

**Comment by wcwang** [comment]
Please follow the [instructions](https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows) to enable Intel VT-x from BIOS and the [steps](https://github.com/intel/haxm/blob/master/docs/manual-windows.md) to disable Hyper-V in Windows first and then try again. Feel free to let us know if you encounter any issues further. Thanks.

**Comment by shahbazgondal** [comment]
I will follow the instructions and I hope it will help me.
Thank you very much, I will let you know if I feel any other difficulty.
