### ISSUE TITLE
haxm cannot be installed

### ISSUE THREAD

**Issue by imene23** [intel/haxm#265]
**Describe the Bug**

Summary: 

**Host Environment**

* HAXM version: 

* Host OS version: 

* Host OS architecture: x86\_64

* Host CPU model: 

* Host RAM size: 

* (Optional) Host computer model: 

**Guest Environment**

* Android Emulator or QEMU version: 

* Guest OS version: 

* Guest OS architecture: 

**To Reproduce**

1. 
2. 
3. 

**Expected Behavior**

Expectation: 

**Reproducibility**

**Diagnostic Information**

Host crash dump: 

HAXM log: 

Android Emulator or QEMU log: 

Screenshots: 

**Additional context**

bonjour tout le monde , j'ai installer android studio mais j'ai un problème d'installation intel haxm , je peut pas l'installer ni à partir de sdk manager ni à partir la répertoire sdk , le message d'erreur m'a dit :" this computer does not support intel virtualization technology or it is being exlusively used by hyper v , haxm cannot be installed", j'ai essayé d'activer la virtualisation à partir de la bios mais je ne trouve pas (j'ai un pc lenovo windows 10 processus AMD E1-6010 with AMD radeon R2 graphics) j'ai essayé aussi de désactiver l'hyper v mais windows montre qu'il n'est pas activé . quelqu'un m'aide s'il vous plait

**Comment by wcwang** [comment]
Thanks for your reporting. Currently HAXM only supports Intel x86 CPU. For more information, you may refer to the homepage on GitHub.

**Comment by wayne-ma** [comment]
Hi @imene23 ,the CPU supports Intel-VT is a must for HAXM. You can refer to the [Windows guide](https://github.com/intel/haxm/blob/master/docs/manual-windows.md) once you get a supported PC.

**Comment by wayne-ma** [comment]
Close it here as it is not the HAXM issue.
