### ISSUE TITLE
Unable to install on Dell XPS 13

### ISSUE THREAD

**Issue by Flat** [intel/haxm#269]
**Describe the Bug**

Summary: the Intel HAXM installer fails to install stating the system does not support VT-x

**Host Environment**

* HAXM version: 7.5.6

* Host OS version: Windows 10 Pro version 1909 Build 18363

* Host OS architecture: x86\_64

* Host CPU model: i7-10710U

* Host RAM size: 16GB

* (Optional) Host computer model: New Dell XPS 13

**Guest Environment**

**To Reproduce**

1. Try to install Intel x86 Emulator Accelerator (HAXM Installer) from the android studio SDK Manager on a New Dell XPS 13 

**Expected Behavior**

Expectation: The installer completes successfully and installs HAXM as the i7-10710U supports VT-x.

HAXM log: 

```
﻿=== Logging started: 3/1/2020  16:15:08 ===
This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed.
Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information. 
=== Logging stopped: 3/1/2020  16:15:08 ===
```

**Additional context**

VT and VT-d are enabled in UEFI/Bios. Hyper-V feature is not installed nor enabled.

**Comment by Soitora** [comment]
Encountered the same issue but not on a Dell XPS 13, just a normal PC cabale of having ran it before my re-format.

Intel Core i7 4790K
Windows 10 Pro 1909 18363.657

**Comment by wayne-ma** [comment]
Hi @Flat @Soitora ,
Thanks for raising this issue. Could you try to install the latest HAXM from the [release page](https://github.com/intel/haxm/releases/download/v7.5.6/haxm-windows_v7_5_6.zip). If this approach cannot resolve your issue, could you confirm whether your Dell laptop has the same issue as described in #226?
BTW, there is a known issue page we summarized for the Windows host, maybe you can refer to the "[Tips and Tricks](https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows#tips-and-tricks)" part as the WSL2 and Sand Box should also be disabled first.

**Comment by Flat** [comment]
Thank you for the response. While that issue did not help; after further research it seems Hyper-V was somehow enabled on boot and I had to run `bcdedit /set hypervisorlaunchtype off` in an elevated terminal and reboot. I'm unsure how it was enabled. Sorry for the issue that was unrelated to the project code but I hope it may help others in the future.

**Comment by wayne-ma** [comment]
Hi @Flat , good to know your issue was resolved. Indeed, sometimes we have to disable hyver-V via bcdedit /set hypervisorlaunchtype off ,even we uncheck the hyper-V option in Windows Features list.
