### ISSUE TITLE
Android : Intel x86 Emulator Accelerator HAXM installer - “revision: 7.5.6” update failed

### ISSUE THREAD

**Issue by pratikbutani** [intel/haxm#273]
Recently, I have installed **Android Studio 3.6.1**, I got a recommendation to update SDK and other tools. 

I am trying to update **Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.5.6)** but getting problem as below:

    Packages to install: 
    - Intel x86 Emulator Accelerator (HAXM installer) (extras;intel;Hardware_Accelerated_Execution_Manager)
    Preparing "Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.5.6)".
    Downloading http://dl.google.com/android/repository/extras/intel/haxm-windows_v7_5_6.zip
    "Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.5.6)" ready.
    Installing Intel x86 Emulator Accelerator (HAXM installer) in E:\Android\Android\sdk\extras\intel\Hardware_Accelerated_Execution_Manager
    "Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.5.6)" complete.
    Failed to update status to COMPLETE
    "Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.5.6)" failed.
    Failed packages:
    - Intel x86 Emulator Accelerator (HAXM installer) (extras;intel;Hardware_Accelerated_Execution_Manager)

[![enter image description here][1]][1]

    Failed to update Intel HAXM. For details, please check the installation log: "C:\Users\Administrator\AppData\Local\Temp\1\haxm_log.txt"
    HAXM installation failed. To install HAXM follow the instructions found at: https://software.intel.com/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-windows
    Installer log is located at C:\Users\Administrator\AppData\Local\Temp\1\haxm_log.txt
    Installer log contents:
    === Logging started: 05/03/2020  16:26:11 ===
    Intel HAXM driver instance loaded. Installation could not be continued.
    === Logging stopped: 05/03/2020  16:26:11 ===
    Done

  [1]: https://i.stack.imgur.com/2jbFk.png

**Comment by wayne-ma** [comment]
Hi @pratikbutani , what is your current HAXM verison? Could you try to download and install the release version from below link?
https://github.com/intel/haxm/releases/download/v7.5.6/haxm-windows_v7_5_6.zip
If above steps could not resolve your installation issue, I suggest you should check the [environment requirement ](https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows)on your system.
BTW, Intel-VT should be enabled and hyper-V should be disabled before installing HAXM.

**Comment by nevilad** [comment]
Looks like the issue is solved:
https://stackoverflow.com/questions/60544578/android-intel-x86-emulator-accelerator-haxm-installer-revision-7-5-6-upda

**Comment by mhq96** [comment]
It didn't work for me

**Comment by wayne-ma** [comment]
Hi @mhq96 ,so what is your problem? Could you raise a new issue? And add  the detail steps &configurations.

**Comment by mhq96** [comment]
> Hi @mhq96 ,so what is your problem? Could you raise a new issue? And add the detail steps &configurations.


![Bug](https://user-images.githubusercontent.com/64631525/83491459-399b0b00-a4cb-11ea-9f3e-392b2f412367.PNG)

**Comment by nevilad** [comment]
Haxm does not support AMD processors. File a bug against Android Studio. There are hypervisors for AMD CPUs and Android Studio can work with these.

**Comment by satanpgn** [comment]
> Haxm does not support AMD processors. File a bug against Android Studio. There are hypervisors for AMD CPUs and Android Studio can work with these.
what kind of bug against studio
