### ISSUE TITLE
Intel HAXM is not installed in Android studio although after installing it manually from github repository.

### ISSUE THREAD

**Issue by Manishkumar2019** [intel/haxm#274]
After updating the android studio.  This Intel Haxm not installed problem occurred. Before that it was working fine.
<img width="386" alt="msiexec_NvCsluLZbB" src="https://user-images.githubusercontent.com/46292851/76517183-f2c9e600-6484-11ea-9b92-70750efa517b.png">

As you can see that it is installed on the system. but after opening the android studio, it is again asking to install the Intel Haxm.
<img width="761" alt="studio64_oVedPgfWrP" src="https://user-images.githubusercontent.com/46292851/76517325-33296400-6485-11ea-8d52-bd91e22a4131.png">

<img width="676" alt="studio64_qs5f6CfZWI" src="https://user-images.githubusercontent.com/46292851/76517343-3ae90880-6485-11ea-92d8-83be91a9522f.png">

Also there is showing no virtualization support. 

![InkedSpeccy64_seVw07rdvG_LI](https://user-images.githubusercontent.com/46292851/76518411-2ad22880-6487-11ea-98a7-1b474f55ec32.jpg)

How can I solve this issue???

**Comment by wayne-ma** [comment]
Hi @Manishkumar2019 , thanks for reporting this issue. It is weird that your CPU shows virtualization 'Not supported'. May I know more info from your side? Thanks in advance.
1. What is your Android studio version?Canary or Stable?What is the version number you are using now?
2. Could you use HAXM before upgrading the Android studio?
3. What is your host OS version? 
4. Could you try to download and install the release version from the [HAXM release page](https://github.com/intel/haxm/releases/download/v7.5.6/haxm-windows_v7_5_6.zip)?
5. As Hyper-V,Sandbox,Windows Hypervisor Platform(WHPX) and Windows Subsystem for Linux 2 (WSL2) conflict with HAXM, please disable them on Windows 10 build 1903 or higher version.

**Comment by Manishkumar2019** [comment]
First up all thanks for your response wayne-ma. Ya i can share you the answer you have asked...

1.  you can see here the details of the android studio after updating it.

<img width="737" alt="and" src="https://user-images.githubusercontent.com/46292851/76600888-eea6d280-652f-11ea-8d6f-a4e390762e9f.png">

2. yes, i was able to use HAXM before upgrading the android studio. I was working on some Flutter related projects and also the android emulator was working fine.

3. Here is the host OS version below.

<img width="431" alt="host" src="https://user-images.githubusercontent.com/46292851/76601291-b784f100-6530-11ea-9e3b-0c65166e9869.png">

4. ya  i have downloaded  and installed the HAXM file from the HAXM release page and also installed it.

<img width="882" alt="hhh" src="https://user-images.githubusercontent.com/46292851/76601645-73deb700-6531-11ea-9be6-3437d230b422.png">

As it is showing is showing above that it is installed on the system. but in Android studio it is not installed. and asking to install intel HAXM. i don't know why?

5. i have tried different method for disabling Hyper-v and also disabled it. but i dont. know how to fully disable it.
     i have tried from windows power shell and command  prompt. like using this code:
     bcdedit /set hypervisorlaunchtype off

  And also in windows feature there is Windows hyper visor option but no hyper-v option.
  
<img width="347" alt="OptionalFeatures_1N0EJSSc04" src="https://user-images.githubusercontent.com/46292851/76602186-81e10780-6532-11ea-992e-4212474eafd5.png">


How can i solve this issue. so i can run again the android emulator in Android studio??

**Comment by wayne-ma** [comment]
> First up all thanks for your response wayne-ma. Ya i can share you the answer you have asked...
> 
> 1. you can see here the details of the android studio after updating it.
> 
> <img alt="and" width="737" src="https://user-images.githubusercontent.com/46292851/76600888-eea6d280-652f-11ea-8d6f-a4e390762e9f.png">
> 
> 1. yes, i was able to use HAXM before upgrading the android studio. I was working on some Flutter related projects and also the android emulator was working fine.
> 2. Here is the host OS version below.
> 
> <img alt="host" width="431" src="https://user-images.githubusercontent.com/46292851/76601291-b784f100-6530-11ea-9e3b-0c65166e9869.png">
> 
> 1. ya  i have downloaded  and installed the HAXM file from the HAXM release page and also installed it.
> 
> <img alt="hhh" width="882" src="https://user-images.githubusercontent.com/46292851/76601645-73deb700-6531-11ea-9be6-3437d230b422.png">
> 
> As it is showing is showing above that it is installed on the system. but in Android studio it is not installed. and asking to install intel HAXM. i don't know why?
> 
> 1. i have tried different method for disabling Hyper-v and also disabled it. but i dont. know how to fully disable it.
>    i have tried from windows power shell and command  prompt. like using this code:
>    bcdedit /set hypervisorlaunchtype off
> 
> And also in windows feature there is Windows hyper visor option but no hyper-v option.
> 
> <img alt="OptionalFeatures_1N0EJSSc04" width="347" src="https://user-images.githubusercontent.com/46292851/76602186-81e10780-6532-11ea-992e-4212474eafd5.png">
> 
> How can i solve this issue. so i can run again the android emulator in Android studio??

Hi @Manishkumar2019 ,it is a pity that I still could not reproduce your issue on my side. As I don't have a win10 home version os, I tired with the win10 enterprise and pro verison, I don't think it is related to the windows host OS version. Could you do more try as my below suggestions?
1. After running 'bcdedit /set hypervisorlaunchtype off' in command prompt ,then reboot your host PC(reboot is a must). And check the hypervisorlaunchtype status was set to off via 'bcdedit -v' in the command prompt terminal.
2. Remove/Uninstall haxm either with Android studio UI or the haxm script in command terminal.
eg.$silient_install.bat -u
3. Install the haxm again either with Android studio or manually with haxm script. eg.$silent_install.bat
4. Launch your AVD again with Android Studio.
5.If still fail to launch your AVD ,please try to use command line, you can also refer to the steps from my screen shot.
$emulator-check accel
$emulator -list-avds
$emulator -avd $your_avd -wipe-data
![pr274](https://user-images.githubusercontent.com/8055260/76819995-bca1b300-6844-11ea-8c51-6eedc7fb2361.PNG)

**Comment by Manishkumar2019** [comment]
Thank you @wayne-ma for your support, i have fixed the android emulator now. 
<img width="384" alt="cxM2B5gWNh" src="https://user-images.githubusercontent.com/46292851/76843692-3eed9f80-6864-11ea-956f-29d94dc0af4a.png">

so fix the issue, i tried to delete the emualator from C:\Users\Dell\AppData\Local\Android\Sdk\emulator  in my local folder then after that
I opened the android studio again and re-installed the emulator again and it was installed finally.
And also with that intel HAXM was also installed on the system through android studio.

**Comment by wayne-ma** [comment]
@Manishkumar2019 So exiting to know that you fixed the issue, now let us close it here.

**Comment by Marquis142** [comment]
hello please help to install Haxm

**Comment by Manishkumar2019** [comment]
@Marquis142 , what type of issues are you having while installing intel HAXM?

**Comment by navkaurz** [comment]
i am facing somewhat same error. hope you guys can help me.

**Comment by wayne-ma** [comment]
> i am facing somewhat same error. hope you guys can help me.

Hi @navkaurz ,please raise a new issue and provide the details.

**Comment by hobbymind** [comment]
hi I too got similar issue,i had installed android studio and installed virtual device the install intel Haxm is coming but i had installed it and it was showing successfully installed but we i try to open virtual device it is showing again

**Comment by wcwang** [comment]
Thanks for your feedback. Could you install the latest HAXM release package and find the installation log in the %TEMP% folder, then check your system configurations according to the [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations)?

**Comment by hobbymind** [comment]
@wcwang Bro issue resolved the problem was due to virtualization was disabled in BIOS after enabling the HAXM installed successfully.Thanks for your time.

**Comment by AlokUpadhyay1** [comment]
hii i am facing same type error my HAXM is Installed but again says not instlled how to fix it.

**Comment by wcwang** [comment]
Thanks for your report. Could you re-install the latest HAXM release package and find the installation log in the %TEMP% folder, then check your system configurations according to the [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations)?

**Comment by RonaldoSurdi** [comment]
Disable Hyper-V 
and that's it :_)
