### ISSUE TITLE
getting problem while installing HAXM 

### ISSUE THREAD

**Issue by Marquis142** [intel/haxm#276]
hello 
iam getting a problem while installing Haxm in my laptop i follow somw instrution but still not working also after downloaded manualy the HAXM file not showning exe file over there.
also there no any file in my C:\Users\hp\AppData\Local\Android\Sdk\extras\intel folder
![intel folder](https://user-images.githubusercontent.com/61916858/77133805-6f168780-6a8a-11ea-8c10-982498c8bdc4.PNG)
![no exe file](https://user-images.githubusercontent.com/61916858/77133807-70e04b00-6a8a-11ea-8a5f-9ca011ce5977.PNG)
 also there is not hyperV feature in my windows feature 

please resolve this issue asap

**Comment by wayne-ma** [comment]
@Marquis142 , you just downloaded the source code but not the released installer, so there is no exe file.Please download the latest release HAXM version v7.5.6 from the release page,
https://github.com/intel/haxm/releases/download/v7.5.6/haxm-macosx_v7_5_6.zip

**Comment by Marquis142** [comment]
still its not working screenshot attached for your ref.
please help
![Capture](https://user-images.githubusercontent.com/61916858/77165655-c4798580-6ad8-11ea-950a-29fdd75ead36.PNG)

**Comment by Marquis142** [comment]
after runing command bcdedit /set hypervisorlaunchtype off 
its show opreation is succesfully 
while trying to install hxam its shows above mention screenshot

**Comment by nevilad** [comment]
Looks like this issue https://github.com/intel/haxm/issues/266. Try the steps described there.

**Comment by Marquis142** [comment]
can you provide mw the step by step procedure 
please help

**Comment by nevilad** [comment]
See https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows, there are Troubleshooting and Tips and Tricks parts which describe how to solve installation errors.

**Comment by Marquis142** [comment]
still its not working bro
please help and provide me step by step procedure

**Comment by Marquis142** [comment]
can you suggest me how to run this command 

egrep -c '(vmx|svm)' /proc/cpuinfo
its showing 
![Capture1](https://user-images.githubusercontent.com/61916858/77229062-7ab09e00-6bb1-11ea-81aa-1424dba5e3b9.PNG)

**Comment by Marquis142** [comment]
hey please help

**Comment by nevilad** [comment]
Egrep is for Linux and will not run in windows.
What is your CPU? Can you enter your BIOS and check if virtualization is disabled? What is your OS?

**Comment by Marquis142** [comment]
Processor	AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G, 2500 Mhz, 4 Core(s), 4 Logical Processor(s)
i enabled the virtualization from bios.
win10

**Comment by Marquis142** [comment]
still not working

**Comment by nevilad** [comment]
HAX does not support AMD CPUs, only Intel.

**Comment by nevilad** [comment]
You should be able to run Android Emulator without hax, but it will work slow.

**Comment by Marquis142** [comment]
Please tell me how it's work without hax

**Comment by nevilad** [comment]
Try this:
https://stackoverflow.com/questions/31366453/run-android-studio-emulator-on-amd-processor

**Comment by Marquis142** [comment]
still its not working 
there is not hyper-v feature avaible in my laptop
also i enable VT from bios setting
![Capture3](https://user-images.githubusercontent.com/61916858/77249481-4c8d9580-6c67-11ea-8653-b014f486050c.PNG)

**Comment by nevilad** [comment]
Run cmd and enter this command:
systeminfo

**Comment by nevilad** [comment]
What windows edition do you have (Home, Pro, etc)? Can be found in Settings->About window from the start menu.

**Comment by nevilad** [comment]
@Marquis142 have yo solved the problem?

**Comment by Marquis142** [comment]
No still facing same issue VT not supported even after I enable from bios setting
Please help I am not able to run emulator in my laptop

**Comment by nevilad** [comment]
What windows edition do you have (Home, Pro, etc)? Can be found in Settings->About window from the start menu.
Run cmd and enter this command:
systeminfo

**Comment by Marquis142** [comment]
ima using home edition

**Comment by nevilad** [comment]
This link lists requirements for Hyper-V:
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

Windows 10 Enterprise, Pro, or Education.
64-bit Processor with Second Level Address Translation (SLAT).
CPU support for VM Monitor Mode Extension (VT-c on Intel CPUs).
Minimum of 4 GB memory.

Home Edition is not supported, can you upgrade to Windows 10 Enterprise, Pro, or Education?

**Comment by Marquis142** [comment]
previously its working fine but after update its showing that error

**Comment by Marquis142** [comment]
is there any other way to run emulator for home edition

**Comment by Marquis142** [comment]
is there any other way to run emulator for home edition

**Comment by nevilad** [comment]
>previously its working fine but after update its showing that error

Who worked previously - haxm or Hyper-V? After which upgrade it shows the error?

>is there any other way to run emulator for home edition

Haxm and Hyper-V are the only accelerators which can do this with Windows. Haxm needs Intel CPU, Hyper-V the mentioned OS editions.

You can also move to Linux and use Android studio with KVM.

**Comment by Marquis142** [comment]
Who worked previously - haxm or Hyper-V? After which upgrade it shows the error?
>> emulator is working fine but after updates its not working
 
You can also move to Linux and use Android studio with KVM.
>> means i have to change my OS from windos to linux?

**Comment by nevilad** [comment]
Android emulator should be able to run without accelerator, it just runs slower. Is it not running?
What updates you did?

>means i have to change my OS from windos to linux?

Yes. You can install two OSes on same laptop.

**Comment by Marquis142** [comment]
What updates you did?
> its just a monthy or quaterly security update 
you can install two OSes on same laptop.
>how?

**Comment by nevilad** [comment]
>its just a monthy or quaterly security update

Please explain in more detail, what was working, how it does not work after updates and what you tried to do, to overcome it.

**Comment by Marquis142** [comment]
previusly after click on the AVD in android studio my emulator will start its means its showing me the virtual device on my laptop scree.
after some days i get  windows update  and that i updated.
after update clicking on AVD its showning error.
![Capture](https://user-images.githubusercontent.com/61916858/77532642-3e37b780-6ebb-11ea-8dc6-dafcaf3da394.PNG)

**Comment by nevilad** [comment]
>previusly after click on the AVD in android studio my emulator will start its means its showing me the virtual device on my laptop scree.

So you were able to run Android emulator and run your applications there? Did it work fast or slow compared to the host OS or a real device?

>after update clicking on AVD its showning error.

The error you paste is from haxm installer. You are trying to run AVD and haxm installer is launched?

**Comment by Marquis142** [comment]
Did it work fast or slow compared to the host OS or a real device?
>> its working very slow 
The error you paste is from haxm installer. You are trying to run AVD and haxm installer is launched?
>> yes

**Comment by nevilad** [comment]
Did you upgraded Android Studio? What version it is?

**Comment by Marquis142** [comment]
i never tried on real device but very slow on host OS

**Comment by Marquis142** [comment]
3.6.1

**Comment by nevilad** [comment]
Looks like Android Emulator changed something and after updating it installs haxm. See https://github.com/intel/haxm/issues/273.
@wcwang, who is responsible for integration of haxm in Android Studio?

@Marquis142, can you ask on Android Studio support if it is possible to run AVD without haxm? Maybe they have some settings to do that.

**Comment by Marquis142** [comment]
ok will ask to andoird studio support

**Comment by nevilad** [comment]
Try this:
https://androidstudio.googleblog.com/2019/12/emulator-29211-and-amd-hypervisor-12-to.html

**Comment by Marquis142** [comment]
i tried with this after runing silent_install.bat not shwoing any runing state
![Capture5](https://user-images.githubusercontent.com/61916858/77548699-e6a64580-6ed4-11ea-8093-767f9035471b.PNG)

**Comment by nevilad** [comment]
Looks like you did not run cmd with administrator privileges. Right click on cmd.exe and in the context menu select run as administrator.

**Comment by Marquis142** [comment]
no i run cmd in suggested path.
after runing this command it display the state wheather it is runing or stoped.

**Comment by nevilad** [comment]
On the screenshot you posted is a string "Requesting administrator privileges...". The link about installing AMD hypervisor says:
"Open a Windows command console with administrator privilege".
I think you are running cmd without admin privileges. Right click on cmd.exe and in the context menu select run as administrator. Then go to the needed path and run installation bat.

**Comment by nevilad** [comment]
@Marquis142 was you able to install AMD hypervisor?
Have you received answers about haxm installation during AVD run on Android Studio support?

**Comment by Marquis142** [comment]
no any answer from android studio

**Comment by nevilad** [comment]
And AMD hypervisor installation?
Can you post the link with Android Studio question?

**Comment by nevilad** [comment]
@Marquis142 have you got any answer from Android studio support?
