### ISSUE TITLE
Installing HAXM

### ISSUE THREAD

**Issue by Abhi83020** [intel/haxm#285]
[Document1.docx](https://github.com/intel/haxm/files/4397419/Document1.docx)
I am facing issue while installing HAXM in my laptop.
First it shows an error of disable Hyper-V and VT-x installation.
But after successfully disable Hyper-V and Installing VT-x from configuration/SDK manager, it showing below error :
"This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed "
I tried all the possible ways to install it, Please help.
Please find attachment.

RAM : 4 GB
SYSTEM : 64-bit operating system
Processor : AMD A4 PRO-3340B WITH RADEON HD GRAPHICS 2.20 GHZ

**Comment by wayne-ma** [comment]
Hi @Abhi83020 , so far the HAXM supports Intel CPU only. I noticed that your CPU model is AMD, so it could NOT be installed. If possible, could you use an Intel CPU laptop for a try?

**Comment by Abhi83020** [comment]
Please suggest me the way for installing hamx or similar installation in
Android Studio which is compatible with AMD.
