### ISSUE TITLE
Running Intel® HAXM installer Failed to install Intel HAXM. For details, please check the installation log: "C:\Users\ANILKU~1\AppData\Local\Temp\haxm_log10.txt" HAXM installation failed. To install HAXM follow the instructions found at: https://software.intel.com/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-windows Installer log is located at C:\Users\ANILKU~1\AppData\Local\Temp\haxm_log10.txt Installer log contents: === Logging started: 4/17/2020  6:13:36 === This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed.  Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information.

### ISSUE THREAD

**Issue by anilkumarpatel543** [intel/haxm#291]
**Describe the Bug**

Summary: 

**Host Environment**

* HAXM version: 

* Host OS version: 

* Host OS architecture: x86\_64

* Host CPU model: 

* Host RAM size: 

* (Optional) Host computer model: 

**Guest Environment**

* Android Emulator or QEMU version: 

* Guest OS version: 

* Guest OS architecture: 

**To Reproduce**

1. 
2. 
3. 

**Expected Behavior**

Expectation: 

**Reproducibility**

**Diagnostic Information**

Host crash dump: 

HAXM log: 

Android Emulator or QEMU log: 

Screenshots: 

**Additional context**

None

**Comment by wayne-ma** [comment]
Hi @anilkumarpatel543 ,could you provide the detail system info as the bug template? From the log your PC may not support Intel VT or the VT was not enabled corrected. Please try to run 'bcdedit /set hypervisorlaunchtype off' in windows cmd windows with admin privilege then reboot your PC and try to install haxm again.

**Comment by Sheshiyer** [comment]
Hi according to the comment above i have done the bcdedit /set hypervisorlaunchtype off as the admin and rebooted and still get the same error saying its enabled. I have disabled it on the services and also on the app and program features window. 

Is there any other method to installing it?

**Comment by wayne-ma** [comment]
Hi @anilkumarpatel543 @Sheshiyer ,could you provide me below info,especially the CPU model as haxm only supports CPUs models so far.
Host Environment

HAXM version:
Host OS version:
Host OS architecture: x86_64
Host CPU model:
Host RAM size:
(Optional) Host computer model:
Guest Environment

Android Emulator or QEMU version:
Guest OS version:
Guest OS architecture:

**Comment by Sheshiyer** [comment]
HAXM version:
Host OS version: haxm-windows_v7_6_1
Host OS architecture: x86_64
Host CPU model:
Host RAM size:8 GB
(Optional) Host computer model: Asus Gaming Tuf FX505dt
[image: image.png]

Guest Environment

Android Emulator or QEMU version: 30.0.5
Guest OS version: Visual studio Android 25 ARM
Guest OS architecture: 86


Thank you for the reply, I have disabled Hyper-V in the windows features
and in the terminal as admin privileges and restarted and yet get the
same error message. Is there any other alternative to amd processors to run
HAXM?
<https://about.me/sheshiyer?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Shesh Iyer
about.me/sheshiyer
<https://about.me/sheshiyer?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by wayne-ma** [comment]
Hi @Sheshiyer , what is the CPU model for your PC, is it an Intel or AMD ?I could not see your attached picture. Please double confirm the CPU you used. So far HAXM only support Intel CPU, thanks.

**Comment by Sheshiyer** [comment]
Thank you so much for the reply, Im on AMD RYZEN 5 Processor, whats the
alternative if any, TIA

**Comment by wayne-ma** [comment]
Got it. That makes sense to raise error when leveraging HAXM with AMD CPU, so close the issue here.

**Comment by egarifs** [comment]
thanks a lot @wayne-ma 
![haxm install successfully](https://user-images.githubusercontent.com/68508709/112423718-c0281e00-8d65-11eb-89dc-a9fd6d170de8.png)
