### ISSUE TITLE
Haxm does not install with AMD processor

### ISSUE THREAD

**Issue by marciomf** [intel/haxm#292]
Running Intel® HAXM installer
Failed to install Intel HAXM. For details, please check the installation log: "C:\Users\marci\AppData\Local\Temp\haxm_log1.txt"
HAXM installation failed. To install HAXM follow the instructions found at: https://software.intel.com/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-windows
Installer log is located at C:\Users\marci\AppData\Local\Temp\haxm_log1.txt
Installer log contents:
=== Logging started: 18/04/2020  15:35:07 ===
This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed. 
Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information.

=== Logging stopped: 18/04/2020  15:35:07 ===
Done

**Comment by krytarowski** [comment]
This is intel project, not amd.

**Comment by marciomf** [comment]
> This is intel project, not amd.

My Android Studio doesn't have an emulator, how can I do it? my processor is AMD.

**Comment by marciomf** [comment]
I can't install a virtual device

**Comment by marciomf** [comment]
thanks Kamil Rytarowski

**Comment by wayne-ma** [comment]
Yes, HAXM only supports Intel CPUs so far.

**Comment by BaveeswariRamesh** [comment]
Hi All,
My Processor is AMD..I have tried to install HAXM in both the ways (manually and via android studio).But I am unable to install it.Can anyone please help me on this.

error: This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed.
Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information.

**Comment by jcs090218** [comment]
Seems like Android supports AMD hardware acceleration. See https://androidstudio.googleblog.com/2019/12/emulator-29211-and-amd-hypervisor-12-to.html. I think you can run the Android emulator without this package installed if you have AMD CPU.
