### ISSUE TITLE
HAXM with QEMU not able to boot Windows VM

### ISSUE THREAD

**Issue by Sinon434** [intel/haxm#293]
I'm trying to run a Windows 10 64-bit VM in QEMU using HAXM, however it keeps stopping with the error "VCPU shutdown request" when ran. Both QEMU and HAXM are up to date as of the day I'm writing this.

**I'm using this command to run the VM:**

`qemu-system-x86_64 -hda win10.img -accel hax`

I've also tried it with -m for memory, -smp, and -accel tcg instead of hax.

**My host machine has these specs:**

Windows 10 Home 64-bit
Intel Core i7-9750H
16 gigabytes ram

**Comment by nevilad** [comment]
Windows 10 64-bit is not yet supported. Windows 10 32-bit is supported but not yet released.

**Comment by nevilad** [comment]
Seems that Windows 10 32-bit support is released, but only for VMs with one CPU.

**Comment by wayne-ma** [comment]
Close it as it is a WIP feature and track it with PR204.
