### ISSUE TITLE
HP EliteBook 745 Can't install HAXM, Hyper-V diabled but still can't download

### ISSUE THREAD

**Issue by AmnaHabiba** [intel/haxm#297]
Can't run the setup wizard for HAXM as it says VT not supported or is exclusively used by Hyper-V

**Comment by wayne-ma** [comment]
@AmnaHabiba Could you provide the CPU model？ Meanwhile, please try to run 'bcdedit /set hypervisorlaunchtype off' in the windows cmd terminal with admin privilege then  reboot your PC to try install again.

**Comment by wayne-ma** [comment]
@AmnaHabiba ,any update or was your issue resolved?

**Comment by AmnaHabiba** [comment]
Sorry read emails recently, my laptop has an AMD processor instead of an intel processor which I just found out. I'll try running the code you gave me and I'll update you.

**Comment by AmnaHabiba** [comment]
It says access denied even though I am the only one using this device any suggestions?

**Comment by wayne-ma** [comment]
Hi @AmnaHabiba ,actually the HAXM only supports Intel so far.Maybe you could find an alternative for your AMD CPU.

**Comment by AmnaHabiba** [comment]
Yes I am working on getting an intel processor device
