### ISSUE TITLE
Unable to download Haxm

### ISSUE THREAD

**Issue by AnilGupte** [intel/haxm#305]
This is not a bug, but a website/Github issue.  I am unable to download any of the zip files to download Haxm.

I have tried clicking on the links, right-clicking and using Save link as and even using wget with the link below:

https://github.com/intel/haxm/releases/download/v7.6.1/haxm-windows_v7_6_1.zip

I have tried a couple of the older versions as well. I am able to download other zip files from Github.  The only thing I have been able to get is a 1kb file with the following contents:

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Request has expired</Message><X-Amz-Expires>300</X-Amz-Expires><Expires>2020-06-17T08:03:27Z</Expires><ServerTime>2020-06-17T08:04:46Z</ServerTime><RequestId>206B7A25C41E715F</RequestId><HostId>z+3+xvA4xYZvJfN25PhSP3orsqhuZOr9cse/DZ0BX/JnD0A7l7lZkf6f8JmQH/N/asSh3fdrQ9g=</HostId></Error>

What am I doing wrong?

**Comment by wayne-ma** [comment]
Hi @AnilGupte  It is weird, I tried many times locally and the haxm can be downloaded successfully. Could you double check your proxy or change the internet access for a try?

**Comment by bwasim** [comment]
Its working for me as well..

**Comment by AnilGupte** [comment]
I've tried through two different connections.  And I was able to download haxm-master from the "Clone or Download" green button very easily.

Does the error message provide a clue?

BTW, this is no longer a high priority as I was able to fix the probme by uninstalling and reinstalling haxm in Android Studio.
