### ISSUE TITLE
I am absolutely certain that Hyper V is disabled at this point. But still no cigar. Please help 

### ISSUE THREAD

**Issue by amir002001** [intel/haxm#309]
![image](https://user-images.githubusercontent.com/55924754/86042209-d3939c00-ba14-11ea-9dae-d421cf55fb74.png)
Windows Event Viewer says there are no operations.
![image](https://user-images.githubusercontent.com/55924754/86042355-09d11b80-ba15-11ea-846f-b011beaef3f1.png)
Completely turned off in services
![image](https://user-images.githubusercontent.com/55924754/86042437-25d4bd00-ba15-11ea-9840-4569a52c60ea.png)
SysInfo says this but I'm not sure what it means.

Please help I'm about to pull my hair out. HAXM keeps saying Hyper V is enabled. Also, my AMD CPU supports Vt-x and is enabled in BIOS.

**Comment by wayne-ma** [comment]
Oh, I see. Hi @amir002001 ,actually the HAXM only supports Intel CPU so far. Your AMD CPU could not use HAXM even if you enable vt-x and disable Hyper-V.
