### ISSUE TITLE
Contributing to silent_install.bat

### ISSUE THREAD

**Issue by n8felton** [intel/haxm#317]
I noticed that `silent_install.bat` from `haxm-windows_v7_6_1.zip` is not part of this repository. Is `silent_install.bat` available in another repository somewhere to contribute improvements to?

**Comment by wayne-ma** [comment]
Hi @n8felton , thanks for your suggestion. Actually we are working on opensource the haxm installer now, the silent_install.bat will be included then.

**Comment by wayne-ma** [comment]
Close the issue here as we will opensource the installer in the coming days.
