### ISSUE TITLE
v7.6.5 Checking Bug  on Windows, OS version info is not vaild. Now just change system language to English to solve it.

### ISSUE THREAD

**Issue by StevenHobs** [intel/haxm#323]
**Describe the Bug**

Summary: 
When I want to update to the v7.6.5. It stops at Check Environment part.
It logs
> OS version：       - Windows 0.0.0

(checks before this show  * YES)

Then make a log file

And delete this log file(Why do this? I cant read it).

Other words. I have installed the v7.5.6 successfully. This is really odd.

**Host Environment**

* HAXM version: v7.6.5

* Host OS version: win-10  2004 (inner 19041.508)

* Host OS architecture: x86_64

* Host CPU model: Intel Core i5-8250U

* Host RAM size: 8GB

* (Optional) Host computer model: Xiaomi air 13.3

**Comment by StevenHobs** [comment]
Plz ignore my poor English.

**Comment by wcwang** [comment]
Thanks for your report. The log file has been moved to %USERPROFILE%\AppData\Local\Temp\haxm_install-*.log. Could you help to provide the content of the log? Thanks.

**Comment by StevenHobs** [comment]
*log file* content:

```
Version: 7.6.5
Output folder: C:\Program Files\Intel\HAXM
Extract: checktool.exe... 100%
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       *  Yes
VMX enabled         *  Yes
EPT supported       *  Yes
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    *  Yes
OS version          -  Windows 0.0.0
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)
The system requirements are not satisfied.
```

And I did the cmd. It returns `Microsoft Windows [版本 10.0.19041.508]`.

**Comment by StevenHobs** [comment]
I know the problem is the system language. When I changed my sys language into Eng. It can be installed. '版本' is Chinese. The install package can't check it.

**Comment by wcwang** [comment]
Thanks for your trouble shooting. We will resolve it as soon as possible.

**Comment by wcwang** [comment]
We have updated the Windows release package [here](https://github.com/intel/haxm/releases/tag/v7.6.5). Could you change your system back to Chinese language and verify it again? Thanks a lot.

**Comment by StevenHobs** [comment]
Well, when I plan to uninstall it. It checks env again and refused to uninstall itself. 😂

**Comment by wcwang** [comment]
Oh, that is true. You may reinstall HAXM with the new installer and it should be successful to install or uninstall.

**Comment by StevenHobs** [comment]
I try it.This bug has been killed perfectly.Thx!!!

**Comment by wcwang** [comment]
Thanks for your timely verification.

**Comment by YowFung** [comment]
I used the updated version of Windows mentioned [above](https://github.com/intel/haxm/issues/323#issuecomment-696573110), but I got the same error: `The system requirements are not satisfied.`

![image](https://user-images.githubusercontent.com/26346560/111570215-429d6480-87df-11eb-89a9-9e26b90df34a.png)



Log file content:
```log
To reinstall the current version: 7.6.5
Output folder: C:\Program Files\Intel\HAXM
Extract: checktool.exe... 100%
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       *  Yes
VMX enabled         *  Yes
EPT supported       *  Yes
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    *  Yes
OS version          *  Windows 10.0.17763
OS architecture     *  x86_64
Guest unoccupied    -  No. 1 guest(s)
```

My system version:
```txt
Microsoft Windows [版本 10.0.17763.1817]
```
It's also in Chinese.

**Comment by wcwang** [comment]
@YowFung, could you help to check whether there is any Android Emulator or QEMU instance launched? If not, could you reboot your Windows host and try again? Thanks.
