### ISSUE TITLE
prooblema em baixa app

### ISSUE THREAD

**Issue by 11041981** [intel/haxm#325]
Nesta etapa, veja como instalar o Intel® Hardware Accelerated Execution Manager. Ele pode ser adquirido através do site:
por que motivo nos mandam pra esta  tela se não da pra baixar o programa .

**Comment by wayne-ma** [comment]
Hi @11041981 , HAXM can be downloaded and installed from both Android Studio and GitHub. The android emulator could be accelerated by HAXM. If possible, could you describe your question details with English? Thx.

**Comment by Znippet** [comment]
I don't speak portugese, but also have problems downloading the windows installer. The Link in the Readme.md for haxm:
`The latest HAXM release for Windows and macOS hosts are available **here**.`
which is `https://github.com/intel/haxm/releases/latest`
redirects to 
`https://github.com/intel/haxm/releases/tag/checktool-v1.0.0`

That is only the checktool

**Comment by wcwang** [comment]
Thanks for your report. The latest HAXM release can be downloaded [here](https://github.com/intel/haxm/releases). The PR #328 is going to fix it. Thanks.

**Comment by wayne-ma** [comment]
Close it as it is fixed by #328
