### ISSUE TITLE
Check Tool v1.0.0 is an installable tool?

### ISSUE THREAD

**Issue by cristian-programmer** [intel/haxm#329]
Hi everyone, I am something new using this virtualization tool, I have seen that when I download Check Tool v1.0.0 .zip on my machine (win 10), it does nothing, as if it will not work, does it run silently?

When I run CheckTool it doesn't open the typical installation guide, could this be a problem?

**Comment by wcwang** [comment]
Thanks for your feedback. The Check Tool is designed for silent installation use. You can find the usage in [README](https://github.com/intel/haxm/tree/master/CheckTool) if you want to execute it manually. Thanks.

**Comment by cristian-programmer** [comment]
I understand, I thank you very much.

**Comment by wcwang** [comment]
My pleasure. You are welcome.
