### ISSUE TITLE
CheckTool 1.0.0 for Windows not working

### ISSUE THREAD

**Issue by jagomf** [intel/haxm#330]
**Describe the Bug**

Nothing happens upon running recent windows 1.0.0 release executable, neither with elevated privilages nor as a regular user.

Also, distributable checktool-windows-1.0.0.zip does not include any readme file. That's really really poor for Intel.

**Host Environment**

Windows 10 x86_64. Intel Core i7-8550U.

**To Reproduce**

1. Download checktool-windows-1.0.0.zip
2. Unzip the only executable file contained
3. Run executable

**Expected Behavior**

Tool should show system support on VMx, EPT, NX, Hyper-V...

**Comment by wcwang** [comment]
This Check Tool is designed for the silent installation usage. The usage can be found in [README](https://github.com/intel/haxm/tree/master/CheckTool) here. Thanks.

**Comment by jagomf** [comment]
Readme should definitely be distributed inside the zip, otherwise is useless.

**Comment by wcwang** [comment]
Thanks for your suggestion. As the release notes in the download page has contained the README link, we did not add readme.txt in the package again. Anyway, we will consider your suggestion in the future release. Thanks a lot.
