### ISSUE TITLE
Unable to install intel® haxm in android studio

### ISSUE THREAD

**Issue by mohamed136** [intel/haxm#340]
I've done everything to solve this. I have enable Intel virtualization technology in BIOS. Unchecked hype V to disable it. But it's still not installed successfully. What did do wrong? I just wanted to install intel® haxm in android studio.

**Comment by wayne-ma** [comment]
Hi @mohamed136 ,sorry to hear that. So could you provide me your system configuration, eg. cpu model, host os version, haxm version, etc. Follow the issue template is preferred which could help us to narrow down your issue more efficiently. 
BTW , please also try below method to disable hyper-V and reboot your machine 
 Open an elevated (i.e. Run as administrator) Command Prompt.
 $bcdedit /set hypervisorlaunchtype off

**Comment by mohamed136** [comment]
Hello @wayne-ma thanks for helping me , here is all screenshot that might help you.

![Screenshot_17](https://user-images.githubusercontent.com/42202937/102316271-8a58e980-3f6d-11eb-8279-4910c21ef4f8.png)

![Screenshot_16](https://user-images.githubusercontent.com/42202937/102316272-8af18000-3f6d-11eb-9d1d-99e0951cd67d.png)

![Screenshot_15](https://user-images.githubusercontent.com/42202937/102316274-8af18000-3f6d-11eb-8da1-83ba9cc6fbca.png)

![Screenshot_14](https://user-images.githubusercontent.com/42202937/102316276-8b8a1680-3f6d-11eb-975d-bb9bab5f71d2.png)

**Comment by wayne-ma** [comment]
Hi @mohamed136 , I noticed that you are using an AMD CPU, but the HAXM only supports Intel CPU so far. 
Meanwhile, you should remove the "$" in the cmdline terminal. eg. type "bcdedit /set hypervisorlaunchtype off".

**Comment by mohamed136** [comment]
![image](https://user-images.githubusercontent.com/42202937/102614853-de5dfc80-412c-11eb-97ef-08502d1d7531.
png)
Hi @wayne-ma It will say this message

**Comment by mohamed136** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/42202937/102615199-680dca00-412d-11eb-8328-9e174f8a0676.png)
Hi @wayne-ma It will say this message

**Comment by wayne-ma** [comment]
> ![Screenshot_18](https://user-images.githubusercontent.com/42202937/102615199-680dca00-412d-11eb-8328-9e174f8a0676.png)
> Hi @wayne-ma It will say this message

Hi @mohamed136 , you should use admin privilege and run as administrator when type the cmd. The important point is that HAXM could NOT support AMD cpu.

**Comment by mohamed136** [comment]
> > ![Screenshot_18](https://user-images.githubusercontent.com/42202937/102615199-680dca00-412d-11eb-8328-9e174f8a0676.png)
> > Hi @wayne-ma It will say this message
> 
> Hi @mohamed136 , you should use admin privilege and run as administrator when type the cmd. The important point is that HAXM could NOT support AMD cpu.

I will get a new laptop which supports Intel®.

**Comment by wayne-ma** [comment]
> > > ![Screenshot_18](https://user-images.githubusercontent.com/42202937/102615199-680dca00-412d-11eb-8328-9e174f8a0676.png)
> > > Hi @wayne-ma It will say this message
> > 
> > 
> > Hi @mohamed136 , you should use admin privilege and run as administrator when type the cmd. The important point is that HAXM could NOT support AMD cpu.
> 
> I will get a new laptop which supports Intel®.

Run Command Prompt with Administrator is the MUST if you use bcdedit cmd.
