### ISSUE TITLE
The link on the main page to the latest HAXM goes to CheckTool instead

### ISSUE THREAD

**Issue by Stokestack** [intel/haxm#342]
**Describe the Bug**
The link presented under Downloads for the latest version of HAXM actually goes to CheckTool instead: https://github.com/intel/haxm/releases/tag/checktool-v1.0.0
 

Summary: 
The link to get the latest HAXM on the main project page is wrong.

**Host Environment**
N.A.

**To Reproduce**

Browse to https://github.com/intel/haxm
Click on "here" in the Downloads section.

**Expected Behavior**

Expectation: 
A page offering the latest version of HAXM, as described.

**Reproducibility**
Always

**Diagnostic Information**

N.A.

**Additional context**

None

**Comment by wcwang** [comment]
Thanks for your report. You may download the latest release [here](https://github.com/intel/haxm/releases). We will update the web page later.

**Comment by wayne-ma** [comment]
@Stokestack Nice issue you raised, thanks a lot.
@wcwang ,maybe we could change hyperlink  to [here](https://github.com/intel/haxm/releases) ( 'https://github.com/intel/haxm/releases')

**Comment by ThreePalmTrees** [comment]
Wow intel
<img src="https://media1.tenor.com/images/73c9ad4cdb095d006ac07db206cbac1a/tenor.gif?itemid=7847084" width="200" />

**Comment by wcwang** [comment]
This issue has been fixed by PR #348. Thanks again.

**Comment by Stokestack** [comment]
You're welcome! Thanks for fixing it.
