### ISSUE TITLE
HAXM fails to install

### ISSUE THREAD

**Issue by awesomeer** [intel/haxm#352]
HAXM fails to install for no apparent reason

Summary:
HAXM fails to install, the error message is "The system requirements are not satisfied.". I have actually installed HAXM successfully and was able to use it with the QEMU command-line below, but now I get the following error message

C:\Users\mithi\Desktop\qemu>qemu-system-x86_64.exe -smp 8 -m 4G -accel hax -hda .\current.img -vga vmware
Failed to open the HAX device!
Open HAX device failed
Failed to get Hax capability:6u
No accelerator found.
qemu-system-x86_64.exe: -accel hax: failed to initialize hax: Invalid argument

I tried uninstalling HAXM through control panel, but I got the same error message: "The system requirements are not satisfied". So I deleted the installation folder (I still have it in my recycle bin). I tried reinstalling again to avail.

This is the installation log
Version: 7.6.5
Output folder: C:\Program Files\Intel\HAXM
Extract: checktool.exe... 100%
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       -  No
VMX enabled         -  No
EPT supported       -  No
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    -  No
OS version          *  Windows 10.0.18363
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)
The system requirements are not satisfied.

**Host Environment**: Windows 10

**Guest Environment**: Ubuntu 20.04 LTS

QEMU version:  5.2.0
* Guest OS version:  Ubuntu 20.04 LTS
* Guest OS architecture: x86_64

**To Reproduce**

1.  qemu-system-x86_64.exe -smp 8 -m 4G -accel hax -hda .\current.img -vga vmware
2. 
3. 

**Expected Behavior**

Expectation: 

**Reproducibility**
I have no idea how to reproduce, bug occurred inexplicably 

**Diagnostic Information**
HAXM log: 

Android Emulator or QEMU log:  
Failed to open the HAX device!
Open HAX device failed
Failed to get Hax capability:6u
No accelerator found.

**Comment by wayne-ma** [comment]
Hi @awesomeer , from your installation log, I noticed that you did not disable Hyper-V before installing HAXM. Please disable Hyper-V and re-install haxm after reboot your PC. The best way to disable hyper-v is using the cmd 'bcdedit /set hypervisorlaunchtype off' with admin.
e.g. 
C:\WINDOWS\system32>bcdedit /set hypervisorlaunchtype off
The operation completed successfully.

**Comment by awesomeer** [comment]
Thank you so much, that fixed my problem. Apparently updating windows messed it up since that is what I did before QEMU stopped working.
