### ISSUE TITLE
The system requirements are not satisfied - HAXM installation failed

### ISSUE THREAD

**Issue by hereisjai** [intel/haxm#369]
Hyper- V disabled. But gives me the error anyways. Please help in HAXM installation

Version: 7.6.6
Output folder: C:\Program Files\Intel\HAXM
Extract: checktool.exe... 100%
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       *  Yes
VMX enabled         -  No
EPT supported       *  Yes
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    *  Yes
OS version          *  Windows 10.0.19042
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)

**Comment by profseb** [comment]
Me too

**Comment by hereisjai** [comment]
My issue got resolved. I had to enable VMX.

**Comment by demberto** [comment]
VMX is nothing but Intel Vt-x/AMD-V. You need to enable it from BIOS, depending on your motherboard it can have various names like "Intel VIrtualisation Technology", "Vanderpool", "Intel VT-x" etc

**Comment by wayne-ma** [comment]
Good to know,your issue was resolved by enable VT. Yes, it is must for haxm installation. So let's close this issue here.
