### ISSUE TITLE
Install Haxm failed

### ISSUE THREAD

**Issue by Phyzait** [intel/haxm#370]
Version: 7.6.6
Output folder: C:\Program Files\Intel\HAXM
Extract: checktool.exe... 100%
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       *  Yes
VMX enabled         *  Yes
EPT supported       *  Yes
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    *  Yes
OS version          *  Windows 10.0.18362
OS architecture     *  x86_64
Guest unoccupied    -  No. 1 guest(s)

**Comment by demberto** [comment]
Check in task manager if you have any startup entry for **Host Services x64**. If there is, disable it and restart your device. You should be able to install HAXM now. If you don't see such an entry, then idk the cause of this issue. Do you have any type of emulator installed?

**Comment by Phyzait** [comment]
I installed Qemu...
I installed Haxm successfully after I shut it down.
Thank u!

**Comment by Phyzait** [comment]
> Check in task manager if you have any startup entry for **Host Services x64**. If there is, disable it and restart your device. You should be able to install HAXM now. If you don't see such an entry, then idk the cause of this issue. Do you have any type of emulator installed?

I installed Qeum...
I installed Haxm successfully after I shut it down.
Thank u!
