### ISSUE TITLE
haxm install VMX enabled

### ISSUE THREAD

**Issue by x13xxxswatxxx** [intel/haxm#374]
haxm install 
CPU VMX supported   Yes 
the processor supports vmx, the BIOS has vt-d, but I could not find how to enable vmx

Output folder: C:\Program Files\Intel\HAXM
Extract: checktool.exe
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       *  Yes
**_VMX enabled         -  No_**
EPT supported       *  Yes
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    *  Yes
OS version          *  Windows 10.0.19042
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)
Execute: cmd.exe /c type "C:\Users\x13xx\Downloads\haxm-windows_v7_6_6\haxm_install-20210501_2024.log" > "C:\Users\x13xx\AppData\Local\Temp\haxm_install-20210501_2024.log"
Delete file: C:\Users\x13xx\Downloads\haxm-windows_v7_6_6\haxm_install-20210501_2024.log

**Comment by wayne-ma** [comment]
Hi @x13xxxswatxxx  ,could you provide more details about your PC info? e.g. CPU model, windows version, emulator&android image version.
Meanwhile, please also try to download and install haxm via haxm release pagehttps://github.com/intel/haxm/releases. Checktool can list your PC configuration.
