### ISSUE TITLE
HAXM installation problem

### ISSUE THREAD

**Issue by Sanjana110278** [intel/haxm#379]
Hello,
I am trying to install Intel HAXM on my computer but during the setup process I am receiving a dialog box stating that 'The system requirements are not satisfied'.
What should I do?

**Comment by wcwang** [comment]
Thanks for your questions. This [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations) may help you to resolve installation issues.
