### ISSUE TITLE
Installation failed (The system requirements are not satisfied.)

### ISSUE THREAD

**Issue by gerryge** [intel/haxm#388]
Hi there,
I have problem with installing HAXM in my windows 10 OS.

Details please see below logs:
Version: 7.6.5
Output folder: C:\Program Files\Intel\HAXM
Extract: checktool.exe... 100%
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       -  No
VMX enabled         -  No
EPT supported       -  No
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    -  No
OS version          *  Windows 10.0.19041
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)
The system requirements are not satisfied.

I have also tried v7.7.0, the same error and I have checked the [System Requirements](https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows#System_Requirements)
Thanks.

![image](https://user-images.githubusercontent.com/6952917/120898986-f6382700-c65f-11eb-88cd-a803b0ebf136.png)
![image](https://user-images.githubusercontent.com/6952917/120898992-02bc7f80-c660-11eb-9d81-7a595d7e5a60.png)

![image](https://user-images.githubusercontent.com/6952917/120899100-97bf7880-c660-11eb-9166-70fb5414e46e.png)

**Comment by wayne-ma** [comment]
Hi @gerryge ,seems you did not enable VT in Bios and did not disable Hyper-V on your platform. Please enable VT in BIOS ,then type 'bcdedit /set hypervisorlaunchtype off' in cmd terminal with admin, then reboot you PC for a try again.

**Comment by orion78fr** [comment]
FYI, I had the same problem (VMX support enabled in bios but showing disabled in the checker, Hyper-V disabled but showing not disabled in checker, windows saying another hypervisor is running in `msinfo32`).
The thing I had to do to fix this is disabling the Virtualbox Network Adapter in the network cards and reboot. Hope this helps !

**Comment by gerryge** [comment]
Hi @wayne-ma, Thanks for you reply.
Actually, I have enabled the VT and disabled the Hyper-V.

![image](https://user-images.githubusercontent.com/6952917/121915443-cb3b8a80-cd65-11eb-8cdd-3ac28de671d5.png)

![image](https://user-images.githubusercontent.com/6952917/121915724-0f2e8f80-cd66-11eb-8217-bcd43be4a5a6.png)

**Comment by gerryge** [comment]
@orion78fr  Thank you very much.
Your approach worked！👍
One thing I need to add is don't forget to restart after disable all the  "*Network Adapter"

![image](https://user-images.githubusercontent.com/6952917/121919154-510d0500-cd69-11eb-895b-5dccc519f01f.png)
![image](https://user-images.githubusercontent.com/6952917/121919225-61bd7b00-cd69-11eb-8145-8d2b89f41a41.png)
