### ISSUE TITLE
Doesn't meet requirements

### ISSUE THREAD

**Issue by mahin557** [intel/haxm#389]
**Describe the Bug**

Summary: 
Tried Everything 
nothing is working 

Output folder: C:\Program Files\Intel\HAXM
Extract: checktool.exe
Execute: C:\Program Files\Intel\HAXM\checktool.exe --verbose
CPU vendor          -  AuthenticAMD
Intel64 supported   *  Yes
VMX supported       -  No
VMX enabled         *  Yes
EPT supported       *  Yes
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    *  Yes
OS version          *  Windows 10.0.19042
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)
Execute: cmd.exe /c type "D:\Dataset\haxm-windows_v7_7_0\haxm_install-20210626_1719.log" > "C:\Users\Admin\AppData\Local\Temp\haxm_install-20210626_1719.log"
Delete file: D:\Dataset\haxm-windows_v7_7_0\haxm_install-20210626_1719.log

WHAT SHOULD I DO ?

**Host Environment**

* HAXM version: 

* Host OS version: 

* Host OS architecture: x86\_64

* Host CPU model: 

* Host RAM size: 

* (Optional) Host computer model: 

**Guest Environment**

* Android Emulator or QEMU version: 

* Guest OS version: 

* Guest OS architecture: 

**To Reproduce**

1. 
2. 
3. 

**Expected Behavior**

Expectation: 

**Reproducibility**

**Diagnostic Information**

Host crash dump: 

HAXM log: 

Android Emulator or QEMU log: 

Screenshots: 

**Additional context**

None

**Comment by nevilad** [comment]
>CPU vendor - AuthenticAMD

HAXM does not support AMD cpus.
