### ISSUE TITLE
Enhancement | Linux version 

### ISSUE THREAD

**Issue by dannyZhou** [intel/haxm#4]
Will we have linux version in the future?

**Comment by raphaelning** [comment]
We don't plan to port HAXM to any Linux host, because for Linux, there's already KVM, which is a mature hypervisor integrated with QEMU.

**Comment by AlexAltea** [comment]
@dannyZhou Just for your information: patch #108 adds Linux host support to HAXM.
On the userland-side, there's QEMU patch queued as well, hopefully to be merged soon:
http://lists.nongnu.org/archive/html/qemu-devel/2018-11/msg01482.html
