### ISSUE TITLE
Does Not Install

### ISSUE THREAD

**Issue by NickDeBeenAIE** [intel/haxm#404]
Where is the Silent_Install.bat file as its not located where the guide tells you to go?

I know:

Nowhere, because its not included anywhere in the folder once extracted.

So how do you install HAXM then?

O.S.:
Windows 11 Pro.

Spec's:

AMD Ryzen 5 3600

Gigabyte (Nvidia) GTX 1080 Ti OC Edition 11gb

32gb Silicon Power Gaming Turbine X 3200mhz.
![Install_silent bat doesn't exist 1](https://user-images.githubusercontent.com/60248725/132086468-a876819e-d839-4d5d-8f0f-7e29cfa36076.png)
![The ONLY file within package](https://user-images.githubusercontent.com/60248725/132086469-6cfe782d-5e5e-41f1-b300-e22c95f192fe.png)

**Comment by wcwang** [comment]
The file silent_install.bat is included in the release package [here](https://github.com/intel/haxm/releases/download/v7.7.0/haxm-windows_v7_7_0.zip). You may install HAXM by executing silent_install.bat in an elevated Command Prompt or running the .exe installer after extracting the release package. By the way, I notice that your CPU brand is AMD but currently HAXM only supports to install on Intel CPU. Thanks for your question.

**Comment by wayne-ma** [comment]
As HAXM does not support AMD CPU, close the issue here.
