### ISSUE TITLE
Setup reports wrong requirements

### ISSUE THREAD

**Issue by matteodev8** [intel/haxm#409]
The Installer reports false information, `Hyper-V disabled - No` but Hyper-V is deactivated. Same goes for EPT, EPT is support but it reports it isn't aviable

**Comment by nevilad** [comment]
Paste a screenshot of the installer screen with these statements. Paste also your cpu model and host OS.

**Comment by wcwang** [comment]
Thanks for your report. You may follow the [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations) to set up the system environment first and try to install HAXM then. Thanks.

**Comment by matteodev8** [comment]
> Paste a screenshot of the installer screen with these statements. Paste also your cpu model and host OS.

![image](https://user-images.githubusercontent.com/59450459/134361159-0ff7bc3f-f7cf-4f86-8a9c-8d7513588c82.png)

**Comment by nevilad** [comment]
Intel Core i7-9700 supports VMX and EPT. Disable Hyper-V as described in the mentioned wiki page. Hopefully this will solve the issue.

**Comment by matteodev8** [comment]
It worked! Thanks!
