### ISSUE TITLE
Wiki Link Dead?

### ISSUE THREAD

**Issue by RVRX** [intel/haxm#410]
**Describe the Bug**
When viewing the wiki page at https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows, the http://software.intel.com/en-us/android **link does not behave as expected and redirects you to a seemingly unrelated page** (furthermore, the page wont even load correctly on firefox, but thats not an issue for this repo). This wiki page is directly linked to when installing Android Studio if the HAXM install fails: `Intel® HAXM installation failed. To install Intel® HAXM follow the instructions found at: https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows`, so it is important that this link works!

Apologies for removing rest of bug template, did not seem necessary in this case.

**Comment by wcwang** [comment]
Thanks for your report. The [wiki page](https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows) has been updated.
