### ISSUE TITLE
Unable to use haxm while docker is installed

### ISSUE THREAD

**Issue by Temepest74** [intel/haxm#419]
I had a problem similar with this guy #361 .
I solved it by running this command `bcdedit /set hypervisorlaunchtype off` and it solved my issue.
At this point in time, I restarted my PC and got an error from docker saying that it needs hyper-v enabled. I enabled it via `bcdedit /set hypervisorlaunchtype auto`. Now, my perminal gives me the following output for haxm:
![image](https://user-images.githubusercontent.com/28103890/144715719-092f0f80-d6c8-405f-8c21-04f9e0c275a4.png)
Any help? I wanna use both applications on the same machine (windows 11 pro)

**Comment by wayne-ma** [comment]
@Temepest74 , HAXM could NOT work with Hyper-V on. If you want to use HAXM  ,you should disable HyperV and run 'bcdedit /set hypervisorlaunchtype off'

**Comment by Temepest74** [comment]
> @Temepest74 , HAXM could NOT work with Hyper-V on. If you want to use HAXM  ,you should disable HyperV and run 'bcdedit /set hypervisorlaunchtype off'

Could you help me with any workaround? 
Is there anything like wsl but with windows instead of linux? 
If not, will it work in a vm?
