### ISSUE TITLE
Not able to install Intel HAXM neither by Android SDK Manager nor manually. PLEASE HELP!

### ISSUE THREAD

**Issue by devayush20** [intel/haxm#434]
**These are the logs during HAXM Installation.**
Preparing "Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)".
Warning: Package "com.android.repository.impl.generated.v2.RemotePackage@44b0bc2c" (extras;intel;Hardware_Accelerated_Execution_Manager) should be installed in 
"D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager" but 
it already exists.
Installing in "D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2" instead.
Downloading https://dl.google.com/android/repository/extras/intel/haxm-windows_v7_6_5.zip
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" ready.
Installing Intel x86 Emulator Accelerator (HAXM installer) in D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" complete.
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" finished.
Parsing D:\ANDROIDSDKINSTALLATION\build-tools\30.0.2\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\build-tools\32.0.0\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\emulator\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2\package.xml
Warning: Observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in inconsistent location 'D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2' (Expected 'D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager')
Warning: Already observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in 'D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager'. Skipping duplicate at 'D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2'
Parsing D:\ANDROIDSDKINSTALLATION\patcher\v4\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\platform-tools\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\platforms\android-32\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\system-images\android-30\google_apis\x86\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\tools\package.xml
Android SDK is up to date.
Running Intel® HAXM installer
**Intel® HAXM installation failed. To install Intel® HAXM follow the instructions found at: https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows**
Done

![image](https://user-images.githubusercontent.com/78680067/149308684-cc04c28b-d315-411a-a214-772665c072bb.png)

**Following is the system configuration:
System Type	x64-based PC
System SKU	0A25
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz, 2419 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.9.0, 08-10-2021
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0PCVD6
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                                           Virtualization Enabled In Firmware: Yes
                                           Second Level Address Translation: Yes
                                           Data Execution Prevention Available: Yes**

I have tried manual install also, but SDK Manager does not detect it.
SERVICE_NAME: intelhaxm
        **TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0**

After installation:
![image](https://user-images.githubusercontent.com/78680067/149308848-5f3c9bcf-b678-4ef7-8c32-682fe4df86c9.png)

**Comment by devayush20** [comment]
I found out that "D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager" does not exist in "D:\ANDROIDSDKINSTALLATION\extras\intel\". I don't know why the SDK Manager is detecting the folder.
Here are the logs:
**Preparing "Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)".
Warning: Package "com.android.repository.impl.generated.v2.RemotePackage@44b0bc2c" (extras;intel;Hardware_Accelerated_Execution_Manager) should be installed in 
"D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager" but 
it already exists.
Installing in "D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2" instead.
Downloading https://dl.google.com/android/repository/extras/intel/haxm-windows_v7_6_5.zip
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" ready.
Installing Intel x86 Emulator Accelerator (HAXM installer) in D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" complete.
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" finished.
Parsing D:\ANDROIDSDKINSTALLATION\build-tools\30.0.2\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\build-tools\32.0.0\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\emulator\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2\package.xml
Warning: Observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in inconsistent location 'D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2' (Expected 'D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager')
Warning: Already observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in 'D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager'. Skipping duplicate at 'D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager-2'
Parsing D:\ANDROIDSDKINSTALLATION\patcher\v4\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\platform-tools\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\platforms\android-32\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\system-images\android-30\google_apis\x86\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\tools\package.xml
Android SDK is up to date.
Running Intel® HAXM installer
Intel® HAXM installation failed. To install Intel® HAXM follow the instructions found at: https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows
Done**
![image](https://user-images.githubusercontent.com/78680067/149351260-04fd08ee-4165-4603-95ed-1a1d009664db.png)
![image](https://user-images.githubusercontent.com/78680067/149350783-fc2eb0ac-2ac7-47d0-bf9e-f2399ff7c1e8.png)
![image](https://user-images.githubusercontent.com/78680067/149350861-929a3967-5d45-4856-8a1f-ef2915babb64.png)


Also, the Android Emulator is not able to detect the HAXM, even after manual installation.
I tried uninstalling Intel HAXM, and reinstalling it using ADV Manager but it failed.

**Preparing "Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)".
Downloading https://dl.google.com/android/repository/extras/intel/haxm-windows_v7_6_5.zip
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" ready.
Installing Intel x86 Emulator Accelerator (HAXM installer) in D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" complete.
"Install Intel x86 Emulator Accelerator (HAXM installer) (revision: 7.6.5)" finished.
Parsing D:\ANDROIDSDKINSTALLATION\build-tools\30.0.2\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\build-tools\32.0.0\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\emulator\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\extras\intel\Hardware_Accelerated_Execution_Manager\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\patcher\v4\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\platform-tools\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\platforms\android-32\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\system-images\android-30\google_apis\x86\package.xml
Parsing D:\ANDROIDSDKINSTALLATION\tools\package.xml
Android SDK is up to date.
Running Intel® HAXM installer
Intel® HAXM installation failed. To install Intel® HAXM follow the instructions found at: https://github.com/intel/haxm/wiki/Installation-Instructions-on-Windows
Done**

**Comment by badri264** [comment]
Faced the same issue today , I tried my level best by disabling hyper v but it doesn't work.  It's better to run your flutter app on real device using USB debugging . Using real device is good enough compare to running the app on a emulator. I will share the video of how to run our flutter app on a real device.

https://youtu.be/BymD9pxtVwY -> Youtube link for running flutter app on a real device.

**Comment by devayush20** [comment]
I am using Android Studio.

Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin

**Comment by wcwang** [comment]
Thanks for your reply. Could you help to find the HAXM installation log in %TEMP%\haxm_install-*.log? And then follow the [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations) to check your host system environment and reinstall HAXM again?

**Comment by devayush20** [comment]
I installed it again using **silent_install.bat** and it worked the next time started Android Studio. The problem is solved.
Thank You!

**Comment by Lamsdeen** [comment]
> 

I tried this and still didnt work for me. Please any hint brother?
