### ISSUE TITLE
Unable to uninstall if hyper-v is enabled

### ISSUE THREAD

**Issue by Temepest74** [intel/haxm#436]
Version 7.6.5.
I have hyper-v enabled and I can not turn it off. I tried to uninstall this program but I got an error. 
![image](https://user-images.githubusercontent.com/28103890/149625816-f5877c51-6c5e-48b8-a6a9-159f6d2af6b9.png)

**Comment by wcwang** [comment]
Thanks for your question. Could you follow the [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations) to check and configurate your environment?

**Comment by Temepest74** [comment]
Yeah, I know I need some stuffs to run your app, but I should not need it to uninstall it

**Comment by wayne-ma** [comment]
@Temepest74 , so far, haxm could not coexisted with Hyper-V. If you need to install/uninstall haxm, you should disable Hyper-V first.

**Comment by Topkek-190** [comment]
Posting what I posted in [#452](https://github.com/intel/haxm/issues/452#issuecomment-1338931767) :

## Uninstall without disabling Hyper-V

### SHORT METHOD (Steps to generate the exe yourself detailed below)
Download [checktool.zip](https://github.com/intel/haxm/files/10163977/checktool.zip), extract, then copy the extracted `checktool.exe` to `%SYSTEMDRIVE%\Program Files\Intel\HAXM`

### LONG METHOD (steps for generating executable in SHORT METHOD for paranoid people)
If we go to `"%SYSTEMDRIVE%\Program Files\Intel\HAXM`, we find executables `uninstall.exe` and `checktool.exe`. If we run 
```
checktool.exe -v
```
We get our system info
```
CPU vendor          *  GenuineIntel
Intel64 supported   *  Yes
VMX supported       -  No
VMX enabled         -  No
EPT supported       -  No
NX supported        *  Yes
NX enabled          *  Yes
Hyper-V disabled    -  No
OS version          *  Windows 10.0.19044
OS architecture     *  x86_64
Guest unoccupied    *  Yes. 0 guest(s)
```
The offending line being
```
Hyper-V disabled    -  No
```
What you need to do is create a new checktool.exe that outputs
```
Hyper-V disabled    -  Yes
```
To make this easy, we'll use a BAT2EXE converter. The one that works in our case is [Advanced Bat 2 EXE](https://www.battoexeconverter.com/)

Download and install the program, then open it from the Start Menu/Desktop
Then paste in the edit bat Window
```
@echo off
echo CPU vendor          *  GenuineIntel
echo Intel64 supported   *  Yes
echo VMX supported       -  No
echo VMX enabled         -  No
echo EPT supported       -  No
echo NX supported        *  Yes
echo NX enabled          *  Yes
echo Hyper-V disabled    -  Yes
echo OS version          *  Windows 10.0.19044
echo OS architecture     *  x86_64
echo Guest unoccupied    *  Yes. 0 guest(s)
```
Then press Ctrl+B or Click on FILE>Build EXE. Then press BUILD EXE in the dialog box.
Save the exe with the name `checktool.exe`, then move the generated `checktool.exe` to 
`"%SYSTEMDRIVE%\Program Files\Intel\HAXM`. Then run the uninstaller file in the same directory and everything should go perfectly
