### ISSUE TITLE
Cannot boot Windows 7 x86 guest due to instruction emulation error

### ISSUE THREAD

**Issue by Pai-Po** [intel/haxm#45]
when i tried boot windows 7 x32 sp1 , i got thus message.
![image](https://user-images.githubusercontent.com/12437819/38729146-97c9412c-3f44-11e8-844f-803a0222b98d.png)
![image](https://user-images.githubusercontent.com/12437819/38729427-8ca78ae6-3f45-11e8-8f91-f2c4fe71c10e.png)
i view the source code and debug it , i found it's  **vcpu_simple_decode** produce it when handle ept violation。it looks like some opcode doesn't support。

**Comment by raphaelning** [comment]
Let's close this one and use #12 to track the instruction emulator bug.

**Comment by Pai-Po** [comment]
thanks。
