### ISSUE TITLE
AMD CPU support

### ISSUE THREAD

**Issue by JayFoxRox** [intel/haxm#5]
*(Feature request)*

*This is a followup to #4 which outright says that no Linux HAXM version is planned because of KVM.*

I'd like to request AMD CPU support or at least wether intel would be willing to accept this into HAXM if implemented by a third party.

**Reasoning**

We already have HAXM and KVM which have small API differences.
For small teams (such as security researchers or hobbyists) it is already a hurdle to add support for both APIs to get their programs cross-platform. For developers it means learning the oddities of both APIs.
I think it would be a sane idea to add a wrapper around KVM, or create a new library called OpenVM or something to get rid of the API differences. But downloading hardware specific drivers would still hurt the end users experience.

If intel does not allow AMD support in HAXM this could lead to yet another API or project. It would also mean releasing different drivers, causing more user experience issues.
AMD VM support on Windows would probably be based on a HAXM fork anyway, so it would lead to unnecessary code duplication, possibly impacting maintainability or even security.

So my question is: Will we ever see AMD CPU support on this repo (not necessarily implemented by intel, but the community or even AMD); or is it against intels vision for HAXM?

**Comment by raphaelning** [comment]
Thanks for this well-written post! I have an answer in mind, but I'd appreciate your patience with the delay in the reply while my manager seeks advice from a few senior colleagues at Intel.

**Comment by raphaelning** [comment]
Sorry for the delay. @joshtriplett who advised us on this matter has prepared a very detailed answer, but it seems to be taking to long for his GitHub account to be associated with Intel and to appear as a project member. Let me just post it on his behalf:

> We don't plan to implement, maintain, or validate this ourselves, but we don't have any objections to seeing another team of developers extend HAXM to support AMD-V. However, while Intel VT and AMD-V serve similar functions, they're different enough that this would be a substantial undertaking, one that would have a major impact on the architecture of the driver. Such support would not be a one-time contribution; it would require detailed architectural discussion in advance of any development, as well as ongoing maintenance, validation, and collaboration. We currently have a full-time team of developers maintaining and validating this driver, with expertise in Intel VT. We'd be willing to work with someone (preferably a team of someones) interested in seeing support for AMD-V, to work out the details for what such support should look like, how it should be maintained *and* validated, and whether it makes more sense to integrate or to maintain a common API across independent drivers. The Linux KVM driver might be a useful source of inspiration here; note that Linux support for VT and AMD-V are in two separate KVM backend drivers with different maintainers.
> 
> Anyone interested in developing, maintaining, validating, and collaborating on such support on an ongoing basis is welcome to contact us, and we can talk about a plan going forward. In the interim, however, I'm going to close this feature request. Thank you for the interest and the request.

**Comment by raphaelning** [comment]
@krytarowski Thanks for pointing us to NVMM, which contains BSD-licensed AMD-V support code. If you want to add AMD-V support to HAXM, please take a moment to read the above post. I imagine it will be a much more intrusive PR to add a second backend (AMD-V, after Intel VT-x) than a fourth frontend (*BSD, after Windows, macOS and Linux), so it is really important to write up a proposal first and discuss it with us.

**Comment by HuErr** [comment]
Winkvm is a very old project, it should be able to support windows for amd after the update 
https://github.com/ddk50/winkvm
