### ISSUE TITLE
Cannot start ubuntu, archlinux ... with hax

### ISSUE THREAD

**Issue by fsmoke** [intel/haxm#74]
I have qemu windows build 2.12.90, haxm 7.2.0. Ubuntu, nor arch linux does not works when i turn on hax acceleration. Permanent kernel panics, black screen freezing and other crashes happens when i run qemu.
Qemu crashed with hax - when i ran it from iso. It crashed on already installed system - it's not matters.

Versions:
archlinux-2018.07.01-x86_64
ubuntu-18.04-live-server-amd64.iso

I run qemu-system-x86_64.exe binary.

`qemu-system-x86_64.exe -drive file=build_slave.img,index=0,media=disk,format=qcow2 -m 2G -accel hax -name build_slave`

My CPU:
core i7 2600k

My Host:
Windows 7 64bit

![2018-07-11_15-49-15](https://user-images.githubusercontent.com/11270831/42575854-04a3490c-852a-11e8-9b42-aef21b1483c5.png)

**Comment by raphaelning** [comment]
Thanks for the report. I don't think we have ever tested an Arch Linux image, so you've probably discovered a HAXM bug. We'll see if we can reproduce this issue on our side tomorrow.

**Comment by fsmoke** [comment]
Thank you for fast answer. So i decided to help you to avoid from full install process of archlinux.

below my build_slave.img packed by 7z and uploaded to yandex disk( it's about ~500mb in archive and 1.8gb unpacked)
[build_slave.7z](https://yadi.sk/d/eF2AI43y3Z4ig4)

system not clean - i already installed some packages(of course with tcg accel) - but it's don't matters 

besides i am developer too - and have mvs on my pc - so i decided to build latest IntelHasm driver myself and test it. But nothing changed, after i replace IntelHaxm.sys in my system directory and reboot. :(

Maybe i did something wrong..?

**Comment by fsmoke** [comment]
I forgot: host machine is win 7 64bit

**Comment by fsmoke** [comment]
As i say i tried ubuntu 18.04 - i installed it with tcg accel, redirected console  to ttyS0(to make log) and then turn on hax - and got... very similar kernel panic 

i attach this log here: 
[run.log](https://github.com/intel/haxm/files/2185350/run.log)

**Comment by dzyong** [comment]
It seems like the same issue as https://github.com/intel/haxm/issues/39.
I met this too on Ubuntu 18.04 and the latest Debian.

**Comment by roc007** [comment]
I have the same issue on the host  Windows 7 64bits, qemu 2.12 haxm 7.2.0 with the guest archlinux 2018.07.01

![qemu_hax_bug](https://user-images.githubusercontent.com/41147669/42625856-1bea7a28-85c9-11e8-951d-501d01558993.png)

**Comment by junxiaoc** [comment]
We could reproduce this issue with attached build_slave.7z. But unfortunately there is no error/warning log in haxm driver when kernel panic happens. We are looking for reasons about what might introduce this issue in haxm.

**Comment by raphaelning** [comment]
> But nothing changed, after i replace IntelHaxm.sys in my system directory and reboot. :(

64-bit Windows 7 won't load a driver unless it's got a legitimate digital signature. When you build HAXM yourself using the Debug build configuration, you only get either a test-signed binary, which is not trusted by Windows. The only way to remove that restriction is to [turn on Test Mode](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option).

You could try a fairly recent 64-bit `IntelHaxm.sys` that we built and signed a few weeks ago:

https://github.com/intel/haxm/issues/40#issuecomment-399031337

**Comment by fsmoke** [comment]
I have test sign mode turned on permanently in my system(cos i developed (and still support) some win driver)- just forgot to say.

**Comment by raphaelning** [comment]
That's great. I'd still recommend that you check out that link and follow the instructions there to download `HaxmLoader.exe`, which can also be used to load the `IntelHaxm.sys` you built.

**Comment by fsmoke** [comment]
just now I tested driver from issue #40 - bad luck - behavior identical :(

**Comment by junxiaoc** [comment]
It looks issue is related with SSE instructions support. We are working on fix.
