### ISSUE TITLE
Unable to destroy VM

### ISSUE THREAD

**Issue by AlexAltea** [intel/haxm#82]
Sometimes, after lots of reinstalling+testing of HAXM while working on it, I encounter one mysterious issue that occurs rather unfrequently (this is the third time that happened to me in the past 3 months). When trying to uninstall the driver, following error shows up:

```
haxm_error:Still VM not be destroyed?
```

This prevents the drivers from being reinstalled and forces me to reboot Windows to continue working on HAXM. I'm still confused as to what causes this issue, or how to debug it. Any ideas would be appreciated.

**Comment by raphaelning** [comment]
Thanks. I've never seen this error on Windows, but it sounds like a pretty severe bug. Similar issues I've seen include:

1. On Mac, we used to fix a bug (probably [this one](https://issuetracker.google.com/issues/62395878#comment26)), where launching a guest (VM creation) would fail without properly destroying the HAXM VM data structures (`vm_t`, etc.), leaving behind a few HAXM-specific devfs nodes. As a result, the HAXM KEXT could not be unloaded without a system reboot. I don't remember the error message, which was probably the same that you quoted. We ended up fixing the VM creation bug, but never the VM destruction bug.
1. On Windows, we used to fix a nasty deadlock bug (#48), where one of the QEMU vCPU thread would block in a HAXM driver call, and even killing the QEMU process would not unblock it. As you could imagine, HAXM driver could not be unloaded without a system reboot, but the difference is that `sc stop` would hang, and HAXM did not have a chance to print that error message.

If we can't reproduce the issue reliably, the best we can do is review the current code and fix any code path that could lead to `hax_put_vm()` not being called.
