### ISSUE TITLE
Intel HAXM Causes macOS 10.13.6 to hang on boot

### ISSUE THREAD

**Issue by joaodforce** [intel/haxm#92]
After many support sessions with apple about me complaining that macOS would hang sometimes while booting we finally came to the conclusion that a 3rd party Kext was causing the system to hang.

At first I doubted it, but upon removing the IntelHAXM kext, The booting issues were resolved.

Im using a 2015 15" Macbook Pro Retina.

After some tries I can get into the OS, but most of the times it hangs there, it looks like booting on verbose mode increases my chances of booting, might be a placebo effect though.

Bellow is an screenshot of where the system hangs while booting. The version installed was 7.2.0

I want to make myself available for further tests if someone has any procedures for me to make in order to help with this issue, or what else can I post in order to help debug this.

![img_8908](https://user-images.githubusercontent.com/9410916/44997823-78fb9700-af87-11e8-95b9-2f4b997139bc.JPG)

**Comment by raphaelning** [comment]
Sorry for the trouble. We really appreciate your reporting this issue to us, and would like to thank you in advance for helping us track it down.

I've never seen macOS boot to a hang, and it may not be straightforward to debug. But there are several things you can do to collect relevant information:

1. You said you installed HAXM 7.2.0 (probably through Android Studio?), but the screenshot shows "HAXM release 6.0.5", which is a very old version. Do you still have a copy of the `intelhaxm.kext` that used to be installed on your system (in `/Library/Extensions/`, although it's not there anymore)? If so, please zip it up and attach it here, so we can determine its version.
1. Do you mind installing the latest HAXM release, [7.3.0](https://github.com/intel/haxm/releases/download/v7.3.0/haxm-macosx_v7_3_0.zip)? I wonder if it still gives you boot problems.
1. In the screenshot, the `kextd stall` messages seem suspicious, and may be related to the hang. If the boot is eventually successful, do these messages also appear in the verbose boot log?
1. I wonder if the system keeps any useful information about unsuccessful boot attempts. The first place to check is `/Library/Logs/DiagnosticReports/`. Here, each file here has a timestamp in its name, so if you remember roughly when a boot hang happened, you could look for files that were generated around that time.
1. Let's also query the system log database using the `log show` command. For example, if the last boot hang occurred on Sep. 1 around 2-4pm, we can use the following query:
   `log show --start '2018-09-01 14:00:00' --end '2018-09-01 16:00:00'`
   Another useful query would be to collect all HAXM activities during a given time frame (please adjust the parameters as you see fit):
  `log show --info --start '2018-08-01' --end '2018-08-31' --predicate 'eventMessage contains "hax"'`

**Comment by joaodforce** [comment]
Thanks for the reply, sorry, the screenshot o posted Is a little old even tough the issue behaves the same, but I believe the version was 7.2.0 since thats what I saw on the bundle version inside the kext, but I might had looked at the wrong thing.

1. I recovered the kext that was installed when I had the issue from my time machine backup and its attached bellow. So you can confirm what version it was, and yes I did installed it from android studio itself back In the day.
[Old IntelHAXM.zip](https://github.com/intel/haxm/files/2348442/Old.IntelHAXM.zip)

2. I Installed the 7.3.0 release form the link you sent me, however the issue did not return, even after multiple reboots, so maybe this version fixed the issue I had, or maybe something needed to be "setup" in order for it to happen, I would wish to try to install the version I attached in order to check if the issue returns, how can I do that? is it just a matter to drop in the `/Library/Extensions` folder, or should I find the original installer in order to have the "full experience"?

3. The verbose flies by too quick if the boot is successful so I cant tell for sure, and I cannot recall a exact time to log into the logs, since there are too many to look at.

4. and 5. If we manage to reproduce the issue we can get down to these steps.

**Comment by HaHoYou** [comment]
2. The installer for 7.2.0 could be find here: https://github.com/intel/haxm/releases 
3. You can try this command: `log show --predicate 'eventMessage contains "hax"'`, if you forget the date and haxm log is not too many.

**Comment by joaodforce** [comment]
Interesting, So I Uninstalled the 7.3.0 version with the `sudo /Library/Extensions/intelhaxm.kext/Contents/Resources/uninstall.sh` command, and installed the 7.2.0 
release and the issue did not come back after all.
While I was researching the issue I came across some thread that says that HAXM silent install was not working properly on macOS high Sierra, so my case might have been an issue where the kext was not properly installed maybe?

I also got to search for the logs, upon looking at it I now remember rebooting on Aug 20th in order to install some software.

Here is a screenshot of It briefly
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/9410916/45067688-8a819380-b09a-11e8-993c-d7d271a12a73.png">

And here is the full Logs in text format. (There might be unrelated info on it though)
[HAXM Logs.txt](https://github.com/intel/haxm/files/2350995/HAXM.Logs.txt)

**Comment by joaodforce** [comment]
Here are the links to the threads I saw before.

[Intel.com](https://software.intel.com/en-us/forums/virtualization-software-development/topic/748379)
[forums.bignerdranch.com](https://forums.bignerdranch.com/t/cant-install-haxm-on-mac-high-sierra-to-create-emulator/13331)

Thanks a lot for the responses, I will keep my HAXM updated and keep my eye on this issue, if it returns I will come back to this thread.

**Comment by raphaelning** [comment]
Thank you, and good luck :) Both threads refer to the `silent_install.sh` bug that was only found in HAXM 6.2.1 and earlier releases.

**Comment by HaHoYou** [comment]
@joaodforce If your bug have not return, shall we close this?

**Comment by joaodforce** [comment]
> @joaodforce If your bug have not return, shall we close this?

Sure thing, the issue never came back after I updated it.

**Comment by wayne-ma** [comment]
Good to know the result, let's close the bug here.
